### ISSUE TITLE
AvalonDock: If you close a document tab before it has been made visible, application will crash with a NullReferenceException

### ISSUE THREAD

**Issue by xceedsoftware** [xceedsoftware/wpftoolkit#1138]
<b>theficus[CodePlex]</b> <br />Use the repro code I've provided in this bug: 
https://wpftoolkit.codeplex.com/workitem/22529

Use quotadd new tabquot to add new tabs
Click quotclosequot button without clicking on the new tab to make it visible. Application will crash with a NullReferenceException. If you click on the tab at least once to give it visibility, this doesn't appear to reproduce.

This is the stack:
   at Xceed.Wpf.AvalonDock.Controls.LayoutItem.get_View()
   at Xceed.Wpf.AvalonDock.DockingManager.RemoveViewFromLogicalChild(LayoutContent layoutContent)
   at Xceed.Wpf.AvalonDock.DockingManager._ExecuteCloseCommand(LayoutDocument document)
   at Xceed.Wpf.AvalonDock.Controls.LayoutDocumentItem.Close()
   at Xceed.Wpf.AvalonDock.Controls.LayoutItem.ltInitDefaultCommandsgtb__24_0(Object p)
   at Xceed.Wpf.AvalonDock.Commands.RelayCommand.Execute(Object parameter)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Booleanamp handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Booleanamp handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Booleanamp handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSGamp msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at System.Windows.Application.Run()
   at AvalonDockTabsTest2.App.Main()

**Comment by xceedsoftware** [comment]
<b>BoucherS[CodePlex]</b> <br />Hi, 

Yes, the community edition is always several versions behind the Plus edition and has fewer controls and features.


――――
Get more controls, features, updates and technical support with 
Xceed Toolkit Plus for WPF

**Comment by xceedsoftware** [comment]
<b>theficus[CodePlex]</b> <br />Am I correct in my understanding that the community edition is several versions behind the plus edition?

**Comment by xceedsoftware** [comment]
<b>BoucherS[CodePlex]</b> <br />Hi, 

I'm also referring to AvalonDock included in the WPF Toolkit. 

Current versions are : 
-WPF Toolkit Plus Edition : v3.3
-WPF Toolkit Community Edition : v3.0. 

WPF Toolkit Plus Edition v3.4 and WPF Toolkit Community Edition v3.1 should be release in the following weeks.


Thanks.
――――
Get more controls, features, updates and technical support with 
Xceed Toolkit Plus for WPF

**Comment by xceedsoftware** [comment]
<b>theficus[CodePlex]</b> <br />I'm using AvalonDock that's part of the WPF Toolkit. Is there a newer version I can use that's publicly available?

**Comment by xceedsoftware** [comment]
<b>BoucherS[CodePlex]</b> <br />Hi, 

This is already fixed. 
The fix is included in v3.1 an up. 

――――
Get more controls, features, updates and technical support with 
Xceed Toolkit Plus for WPF
