### ISSUE TITLE
DateTimePicker control: poor support when using keyboard

### ISSUE THREAD

**Issue by HansSolos** [xceedsoftware/wpftoolkit#1173]
- Setting the UpdateValueOnEnterKey  on False will break the typing functionality in the control.

- When entering a time and the pressing a right arrow to move to the next field or seconds, this exception occurs when the : separator is accidentally deleted:

System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Xceed.Wpf.Toolkit.DateTimeParser.ComputeDateTimeString(String dateTime, String format, DateTime currentDate, CultureInfo cultureInfo)
   at Xceed.Wpf.Toolkit.DateTimeParser.TryParse(String value, String format, DateTime currentDate, CultureInfo cultureInfo, DateTime& result)
   at Xceed.Wpf.Toolkit.DateTimeUpDown.TryParseDateTime(String text, DateTime& result)
   at Xceed.Wpf.Toolkit.DateTimeUpDown.IsCurrentValueValid()
   at Xceed.Wpf.Toolkit.Primitives.DateTimeUpDownBase`1.OnPreviewKeyDown(KeyEventArgs e)
   at System.Windows.UIElement.OnPreviewKeyDownThunk(Object sender, KeyEventArgs e)
   at System.Windows.Input.KeyEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndKeyboardInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawKeyboardActions actions, Int32 scanCode, Boolean isExtendedKey, Boolean isSystemKey, Int32 virtualKey)
   at System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSG& msg, Boolean& handled)
   at System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSG& msg, ModifierKeys modifiers)
   at System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by HansSolos** [comment]
Hi, 

Thank you for the quick feedback.
- My apologies, I was referring to the DateTimeUpDown control for the exception part (hence the stacktrace). I used to reproduce the issue easily last week, but now I can't simulate it anymore.
Maybe it has something to do with CultureInfo (I live in West-Europe, so timeFormat is 24hours).

- When shall the v3.2 be released? shortly, in few weeks, ..?

Thanks in advance

**Comment by XceedBoucherS** [comment]
Hi,

v3.2 Community edition will be released in a few weeks. Stay tuned.
