### ISSUE TITLE
TimePicker crash using v3.1.0

### ISSUE THREAD

**Issue by shabtaisharon** [xceedsoftware/wpftoolkit#1176]
at Xceed.Wpf.Toolkit.DateTimeUpDown.Increment(Int32 step)
   at Xceed.Wpf.Toolkit.DateTimeUpDown.OnIncrement()
   at Xceed.Wpf.Toolkit.Primitives.UpDownBase`1.DoIncrement()
   at Xceed.Wpf.Toolkit.Primitives.UpDownBase`1.OnSpinnerSpin(Object sender, SpinEventArgs e)
   at Xceed.Wpf.Toolkit.Spinner.OnSpin(SpinEventArgs e)
   at Xceed.Wpf.Toolkit.ButtonSpinner.OnButtonClick(Object sender, RoutedEventArgs e)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonDown(MouseButtonEventArgs e)
   at System.Windows.Controls.Primitives.RepeatButton.OnMouseLeftButtonDown(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseDownThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Window.ShowHelper(Object booleanBox)
   at System.Windows.Window.ShowDialog()
   at BlackPearlEonProtect.TaskSchedulingApp.Views.ManageTrigger.Show()
   at BlackPearlEonProtect.TaskSchedulingApp.Views.ManageTask.btnNewTrigger_Click(Object sender, RoutedEventArgs e)

**Comment by XceedBoucherS** [comment]
Hi,

This could already be fixed in latest versions, but could you give more details on how you 've end up with this crash ? I know you are incrementing a TimePicker, but what are the exacts steps resulting in the crash ? Are you using code-behind, the mouse, the keys ?
Thanks.

**Comment by shabtaisharon** [comment]
Hi,
Thank you for your reply.
The steps to reproduce this crash:
1. Click on the colon in the time or the space between the minutes and the (AM/PM) indicator
2. Click the up or down arrow next to it with the mouse

try to do it more than once if you dont crash at the first time

**Comment by XceedBoucherS** [comment]
Hi,

I can reproduce the crash in v3.1.
The DateTime controls have been reviewed in latest versions. For this situation, v3.2 and up do not crash.

To have a quick fix, go in file Xceed.Wpf.Toolkit/DateTimeUpDown/Implementation/DateTimeUpDown.cs, 
in method "Increment",
and right after the line : " var newValue = this.UpdateDateTime( currentValue, step );"
add : 
if( newValue == null )
            return;

Current Toolkit versions are :
-OpenSource : v3.1
-Plus : v3.4

We are in the final stages of releasing Toolkit Plus version v3.5. The OpenSource version will also have a new release pretty soon.

**Comment by shabtaisharon** [comment]
Thank you very much for your help :+1:
