### ISSUE TITLE
TimePicker InvalidOperationException v3.2.0

### ISSUE THREAD

**Issue by lamak4o** [xceedsoftware/wpftoolkit#1194]
System.InvalidOperationException: Nullable object must have a value.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at Xceed.Wpf.Toolkit.DateTimeUpDown.Increment(Int32 step)
   at Xceed.Wpf.Toolkit.DateTimeUpDown.OnIncrement()
   at Xceed.Wpf.Toolkit.Primitives.UpDownBase`1.DoIncrement()
   at Xceed.Wpf.Toolkit.Primitives.UpDownBase`1.OnSpin(SpinEventArgs e)
   at Xceed.Wpf.Toolkit.Primitives.UpDownBase`1.OnSpinnerSpin(Object sender, SpinEventArgs e)
   at Xceed.Wpf.Toolkit.Spinner.OnSpin(SpinEventArgs e)
   at Xceed.Wpf.Toolkit.ButtonSpinner.OnMouseWheel(MouseWheelEventArgs e)
   at System.Windows.UIElement.OnMouseWheelThunk(Object sender, MouseWheelEventArgs e)
   at System.Windows.Input.MouseWheelEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

The steps to reproduce this issue:
- Click on the colon in the time
- Click the up or down arrow next to it with the mouse or use wheel

**Comment by XceedBoucherS** [comment]
Hi,
Are you sure this is happening in v3.2 ?
Trying in v3.1 result in a null ref exception, as you pointed out.
Trying in v3.2 doesn't produce a crash.

**Comment by lamak4o** [comment]
Thanks, it was 3.1.
