### ISSUE TITLE
TimePicker InvalidOperationException v3.2.0

### ISSUE THREAD

**Issue by lamak4o** [xceedsoftware/wpftoolkit#1196]
Exception log:
System.InvalidOperationException: Nullable object must have a value.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at Xceed.Wpf.Toolkit.DateTimeUpDown.Increment(Int32 step)
   at Xceed.Wpf.Toolkit.DateTimeUpDown.OnDecrement()
   at Xceed.Wpf.Toolkit.Primitives.UpDownBase`1.DoDecrement()
   at Xceed.Wpf.Toolkit.Primitives.UpDownBase`1.OnSpin(SpinEventArgs e)
   at Xceed.Wpf.Toolkit.Primitives.UpDownBase`1.OnSpinnerSpin(Object sender, SpinEventArgs e)
   at Xceed.Wpf.Toolkit.Spinner.OnSpin(SpinEventArgs e)
   at Xceed.Wpf.Toolkit.ButtonSpinner.OnMouseWheel(MouseWheelEventArgs e)
   at System.Windows.UIElement.OnMouseWheelThunk(Object sender, MouseWheelEventArgs e)
   at System.Windows.Input.MouseWheelEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

Steps:

1. Select hours and click on down arrow to 00 hours.
2. Click once more on down arrow (hours must be selected).
3. Exception occurred.

**Comment by XceedBoucherS** [comment]
Hi,
I tried with :
 Thread.CurrentThread.CurrentCulture = new System.Globalization.CultureInfo( "fr-CA" );
 Thread.CurrentThread.CurrentUICulture = new System.Globalization.CultureInfo( "fr-CA" );
and in XAML :
<xctk:TimePicker />

In v3.2, I can use the Down button spinner to decrease the hours until "00" and decrease again without a crash.

**Comment by lamak4o** [comment]
Hi, 

Sorry for not fully issue description. TimePicker crashes with the following code in XAML:<WpfToolkit:TimePicker Format="Custom" FormatString="HH:mm:ss" Value="00:00:05" StartTime="00:00:00" EndTime="15:00:00"/>

**Comment by XceedBoucherS** [comment]
Hi,

This is already fixed in v3.3 or later. 
You can temporarly fix it by going in file "Xceed.Wpf.Toolkit/DateTimeUpDown/Implementation/DateTimeUpDown.cs,"
in method "Increment( int step )"
after the line:
var newValue = this.UpdateDateTime( currentValue, step );
add :
if( newValue == null )
            return;

Please note that DateTime controls have all been reviewed from v3.1 to v3.4.

**Comment by RoboticOxygen** [comment]
October 25 2017
version 3.2.0 and 3.1.0 were crashing when using a datetime or datetimeupdown control and selecting punctuation and then trying to use the spinner
"Nullable object must have a value"
I found this: https://github.com/xceedsoftware/wpftoolkit/issues/1196
Using nuget to obtain xceed.wpf.toolkit library version 3.2.0 (latest available) and unable to find any preview version through nuget, 
i was forced to build from source.  tested the binary and the bug was gone.

cloned https://github.com/xceedsoftware/wpftoolkit.git
did the following change and built:

diff --git ExtendedWPFToolkitSolution/Src/Xceed.Wpf.Toolkit/DateTimeUpDown/Implementation/DateTimeUpDown.cs ExtendedWPFToolkitSolution/Src/Xceed.Wpf.Toolkit/DateTimeUpDown/Implementation/DateTimeUpDown.cs
index aba7899..d83c6bd 100644
--- ExtendedWPFToolkitSolution/Src/Xceed.Wpf.Toolkit/DateTimeUpDown/Implementation/DateTimeUpDown.cs
+++ ExtendedWPFToolkitSolution/Src/Xceed.Wpf.Toolkit/DateTimeUpDown/Implementation/DateTimeUpDown.cs
@@ -718,6 +718,7 @@ namespace Xceed.Wpf.Toolkit
         if( currentValue.HasValue )
         {
           var newValue = this.UpdateDateTime( currentValue, step );
+          if( newValue == null )return;//https://github.com/xceedsoftware/wpftoolkit/issues/1196
           this.TextBox.Text = newValue.Value.ToString( this.GetFormatString( this.Format ), this.CultureInfo );
         }
         else

**Comment by XceedBoucherS** [comment]
Hi,

The free version of the Toolkit is always 2-3 versions behind the Plus version.
Current users of the Plus version have v3.5
Current users of the Free version have v3.2
Next available versions will be :
Plus version : v3.6
Free version : v3.3
You can obtain the Plus version here : https://github.com/xceedsoftware/wpftoolkit/wiki/Xceed-Toolkit-Plus-for-WPF

**Comment by RoboticOxygen** [comment]
I already understood the pattern, I just wanted to get snarky about it 👍
