### ISSUE TITLE
Exception when using navigation keys such as Tab or arrow keys while ChildWindow is visible

### ISSUE THREAD

**Issue by xceedsoftware** [xceedsoftware/wpftoolkit#122]
<b>kainhart[CodePlex]</b> <br />I'm seeing the following exception when using navigation keys such as Tab or arrow keys while ChildWindow is visible. I'm running the .NET 3.5 version of the library compiled from source version v1.4.0.
nbsp
System.NotSupportedException was unhandled
Message='Microsoft.Windows.Controls.ChildWindow' is not a valid value for 'Setter.Value'; values derived from Visual or ContentElement are not supported.
Source=PresentationFramework
StackTrace:
   at System.Windows.Setter.Seal()
   at System.Windows.SetterBaseCollection.Seal()
   at System.Windows.Style.Seal()
   at System.Windows.StyleHelper.UpdateStyleCache(FrameworkElement fe, FrameworkContentElement fce, Style oldStyle, Style newStyle, Styleamp styleCache)
   at System.Windows.FrameworkElement.OnStyleChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntryamp newEntry, Boolean coerceWithDeferredReference, OperationType operationType)
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, OperationType operationType, Boolean isInternal)
   at System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
   at System.Windows.Input.KeyboardNavigation.FocusVisualAdorner..ctor(UIElement adornedElement, Style focusVisualStyle)
   at System.Windows.Input.KeyboardNavigation.ShowFocusVisual(DependencyObject element)
   at System.Windows.Input.KeyboardNavigation.ProcessInput(InputEventArgs inputEventArgs)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndKeyboardInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawKeyboardActions actions, Int32 scanCode, Boolean isExtendedKey, Boolean isSystemKey, Int32 virtualKey)
   at System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSGamp msg, Booleanamp handled)
   at System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSGamp msg, ModifierKeys modifiers)
   at System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Boolean isSingleParameter)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Boolean isSingleParameter, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Boolean isSingleParameter)
   at System.Windows.Threading.Dispatcher.Invoke(DispatcherPriority priority, Delegate method, Object arg)
   at System.Windows.Interop.HwndSource.OnPreprocessMessageThunk(MSGamp msg, Booleanamp handled)
   at System.Windows.Interop.ComponentDispatcherThread.RaiseThreadMessage(MSGamp msg)
   at System.Windows.Threading.Dispatcher.TranslateAndDispatchMessage(MSGamp msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunInternal(Window window)
   at WPFToolkit.Extended.Examples.App.Main() in C:\Users\jpierson\Downloads\wpftoolkit-75862\Release\v1.4.0\ExtendedWPFToolkitSolution_35\Src\WPFToolkit.Extended.Examples\obj\Debug\App.g.cs:line 0
   at System.AppDomain._nExecuteAssembly(Assembly assembly, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
InnerException: 
nbsp
nbsp
Below is a simple example app that should be able to reproduce the problem.
nbsp
ltWindow x:Class=quotWPFToolkit.Extended.Examples.Window1quot
    xmlns=quothttp://schemas.microsoft.com/winfx/2006/xaml/presentationquot
    xmlns:x=quothttp://schemas.microsoft.com/winfx/2006/xamlquot
    xmlns:extToolkit=quothttp://schemas.microsoft.com/winfx/2006/xaml/presentation/toolkit/extendedquot
    Title=quotWindow1quot
    Height=quot300quot
    Width=quot300quotgt
ltGridgt
    ltextToolkit:ChildWindow Visibility=quotVisiblequot
                            Height=quot141quot
                            Width=quot168quot
                            IsModal=quotTruequotgt
        ltGridgt
            ltButtongtDo Something!lt/Buttongt
        lt/Gridgt
    lt/extToolkit:ChildWindowgt
lt/Gridgt
lt/Windowgt

**Comment by xceedsoftware** [comment]
<b>brianlagunas[CodePlex]</b> <br />This has been resolved. The fix it I had to remove the FocusVisualStyle in the .NET 3.5 version because the .NET 3.5 framework has a limitation in it that doesn't support using content controls as style setters. Also, do not use the Visibility property
 to control the state of the ChildWindow. Instead use the WindowState property.

**Comment by xceedsoftware** [comment]
Resolved with changeset 76096.

**Comment by xceedsoftware** [comment]
<b>brianlagunas[CodePlex]</b> <br />I easily duplicated this issue. Let me look into it.

**Comment by xceedsoftware** [comment]
<b>kainhart[CodePlex]</b> <br />Same issue on 1.4.0.3.

**Comment by xceedsoftware** [comment]
<b>brianlagunas[CodePlex]</b> <br />Please try the current source version of 1.4.0.3 located in the Main folder in the source structure.
