### ISSUE TITLE
TypeInitializationException when RichTextBoxFormatBar is shown

### ISSUE THREAD

**Issue by chrfin** [xceedsoftware/wpftoolkit#1305]
A customer reported that our software is crashing when the `RichTextBoxFormatBar` is shown.
The logs contain the following stack-trace:

> System.TypeInitializationException: The type initializer for 'System.Windows.Media.Fonts' threw an exception. ---> System.IO.FileFormatException: No FontFamily element found in FontFamilyCollection that matches current OS or greater: Windows7SP1 ---> System.IO.FileFormatException: No FontFamily element found in FontFamilyCollection that matches current OS or greater: Windows7SP1
>    at MS.Internal.FontFace.CompositeFontParser.Fail(String message, Exception innerException)
>    at MS.Internal.FontFace.CompositeFontParser.ParseFontFamilyCollectionElement()
>    at MS.Internal.FontFace.CompositeFontParser..ctor(Stream fileStream)
>    --- End of inner exception stack trace ---
>    at MS.Internal.FontFace.CompositeFontParser.Fail(String message, Exception innerException)
>    at MS.Internal.FontFace.CompositeFontParser..ctor(Stream fileStream)
>    at MS.Internal.FontCache.FamilyCollection.SystemCompositeFonts.GetCompositeFontFamilyAtIndex(Int32 index)
>    at MS.Internal.FontCache.FamilyCollection.GetFontFamilies(Uri fontFamilyBaseUri, String fontFamilyLocationReference)
>    at System.Windows.Media.Fonts.CreateFamilyCollection(Uri fontLocation, Uri fontFamilyBaseUri, String fontFamilyLocationReference)
>    at System.Windows.Media.Fonts..cctor()
>    --- End of inner exception stack trace ---
>    at Xceed.Wpf.Toolkit.Core.Utilities.FontUtilities.<get_Families>d__1.MoveNext()
>    at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
>    at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
>    at MS.Internal.Data.EnumerableCollectionView.LoadSnapshotCore(IEnumerable source)
>    at MS.Internal.Data.EnumerableCollectionView..ctor(IEnumerable source)
>    at MS.Internal.Data.ViewManager.GetViewRecord(Object collection, CollectionViewSource cvs, Type collectionViewType, Boolean createView, Func`2 GetSourceItem)
>    at MS.Internal.Data.DataBindEngine.GetViewRecord(Object collection, CollectionViewSource key, Type collectionViewType, Boolean createView, Func`2 GetSourceItem)
>    at System.Windows.Data.CollectionViewSource.GetDefaultCollectionView(Object source, Boolean createView, Func`2 GetSourceItem)
>    at System.Windows.Data.CollectionViewSource.GetDefaultCollectionView(Object source, DependencyObject d, Func`2 GetSourceItem)
>    at System.Windows.Controls.ItemCollection.SetItemsSource(IEnumerable value, Func`2 GetSourceItem)
>    at System.Windows.Controls.ItemsControl.OnItemsSourceChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
>    at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
>    at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
>    at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
>    at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
>    at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
>    at System.Windows.Controls.ItemsControl.set_ItemsSource(IEnumerable value)
>    at Xceed.Wpf.Toolkit.RichTextBoxFormatBar.OnApplyTemplate()
>    at System.Windows.FrameworkElement.ApplyTemplate()
>    at Xceed.Wpf.Toolkit.RichTextBoxFormatBarManager.ShowAdorner()
>    at Xceed.Wpf.Toolkit.RichTextBoxFormatBarManager.RichTextBox_MouseButtonUp(Object sender, MouseButtonEventArgs e)
>    at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
>    at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
>    at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
>    at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
>    at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
>    at System.Windows.Input.InputManager.ProcessStagingArea()
>    at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
>    at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
>    at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
>    at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
>    at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
>    at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
>    at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
>    at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
>    at System.Windows.Application.RunDispatcher(Object ignore)
>    at System.Windows.Application.RunInternal(Window window)
>    at OurApp.App.Main() System.Object:

**Comment by XceedBoucherS** [comment]
Hi,

Do you have more info on how to reproduce (every time the RichTextBoxFormatBar is shown ? Once in a while ?)
A specific RichTextBox ?
Which operating system ?
What version of the Toolkit ?

Thank you.

**Comment by chrfin** [comment]
Hi,

the customer said it happens every time he selects something in the box (which is the only rich text box in our software).
OS-version I could ask and toolkit-version is the latest version.

Thanks & regards
Christoph
