### ISSUE TITLE
Crash when dragging document out of docking and setting focus on Loaded event

### ISSUE THREAD

**Issue by JobaDiniz** [xceedsoftware/wpftoolkit#1423]
Although I found out about this bug in the [Gemini](https://github.com/tgjones/gemin) repository, it is not related to Gemini's code, as I thoroughly troubleshooted.

It was really hard to figure out why and exact how this happens. See the [video](https://1drv.ms/v/s!AhH0QYI81F61gtsGf8kXeDQpiFbh4g) for better understanding.

In the first part of the video (0-30s) you will see that when dragging document out of the docking, the window does not appear (you'll see nothing) but I can still mouse over the docking manager points where the window could be placed. When I release the _**phantom window**_ back to the document pane an error is thrown (**NullReferenceException**).

The second part of the video, I've commented out the line where the error is happening: `//Loaded += (s,e)=> MoveFocus(new TransversalRequest(FocusNavigationDirection.Next));`. When the code is commented out, the error does not occur and the window is shown just fine.

The error occurs in any `Control` that is within the `DockingManager LayoutItemTemplate` and tries to set `Keyboard.Focus` on the `Loaded` event.

It seems that the error is not related to *AvalonDock* itself, as you can see in the **Stack Trace** below. It seems a combination of steps that leads to an error in the **.net Framework** itself - *not entirely sure though*.

```
   at System.Windows.Interop.HwndKeyboardInputProvider.System.Windows.Input.IKeyboardInputProvider.AcquireFocus(Boolean checkOnly)
   at System.Windows.Input.KeyboardDevice.TryChangeFocus(DependencyObject newFocus, IKeyboardInputProvider keyboardInputProvider, Boolean askOld, Boolean askNew, Boolean forceToNullIfFailed)
   at System.Windows.Input.KeyboardDevice.Focus(DependencyObject focus, Boolean askOld, Boolean askNew, Boolean forceToNullIfFailed)
   at System.Windows.Input.KeyboardDevice.Focus(IInputElement element)
   at Xceed.Wpf.AvalonDock.Controls.FocusElementManager.SetFocusOnLastElement(ILayoutElement model)
   at Xceed.Wpf.AvalonDock.DockingManager.OnLayoutRootPropertyChanged(Object sender, PropertyChangedEventArgs e)
   at System.ComponentModel.PropertyChangedEventHandler.Invoke(Object sender, PropertyChangedEventArgs e)
   at Xceed.Wpf.AvalonDock.Layout.LayoutElement.RaisePropertyChanged(String propertyName)
   at Xceed.Wpf.AvalonDock.Layout.LayoutRoot.InternalSetActiveContent(LayoutContent currentValue, LayoutContent newActiveContent)
   at Xceed.Wpf.AvalonDock.Layout.LayoutRoot.set_ActiveContent(LayoutContent value)
   at Xceed.Wpf.AvalonDock.Layout.LayoutContent.set_IsActive(Boolean value)
   at Xceed.Wpf.AvalonDock.Controls.LayoutDocumentControl.OnPreviewGotKeyboardFocus(KeyboardFocusChangedEventArgs e)
   at System.Windows.UIElement.OnPreviewGotKeyboardFocusThunk(Object sender, KeyboardFocusChangedEventArgs e)
   at System.Windows.Input.KeyboardFocusChangedEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.KeyboardDevice.TryChangeFocus(DependencyObject newFocus, IKeyboardInputProvider keyboardInputProvider, Boolean askOld, Boolean askNew, Boolean forceToNullIfFailed)
   at System.Windows.Input.KeyboardDevice.Focus(DependencyObject focus, Boolean askOld, Boolean askNew, Boolean forceToNullIfFailed)
   at System.Windows.Input.KeyboardDevice.Focus(IInputElement element)
   at System.Windows.UIElement.Focus()
   at System.Windows.Input.KeyboardNavigation.Navigate(DependencyObject currentElement, TraversalRequest request, ModifierKeys modifierKeys, DependencyObject firstElement)
   at System.Windows.FrameworkElement.MoveFocus(TraversalRequest request)
   at Gemini.Modules.CodeEditor.Views.CodeEditorView.<.ctor>b__2_0(Object sender, RoutedEventArgs e) in C:\Users\joberto.diniz\AppData\Local\WDG Automation\downloads\gemini-master\src\Gemini.Modules.CodeEditor\Views\CodeEditorView.xaml.cs:line 17
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   at MS.Internal.LoadedOrUnloadedOperation.DoWork()
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.Resize(ICompositionTarget resizedCompositionTarget)
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```
As a workaround for **Gemini**, they need to set focus _**only once**_. `Loaded` event can occur multiple times, and the error is thrown when dragging, and when dragging the `Loaded` event is fired again.

But @xceedsoftware could try to investigate this further and maybe come up with an workaround themselves.

Related: https://github.com/tgjones/gemini/issues/159#issuecomment-450359455

**Comment by XceedBoucherS** [comment]
Hi,
We are not using Gemini, so I suggest you try with the latest version (v3.7) available here : https://xceed.com/xceed-toolkit-plus-for-wpf/ and see if it still happens.
If yes, we could investigate further.
