### ISSUE TITLE
Zoombox control not working

### ISSUE THREAD

**Issue by Dexter404** [xceedsoftware/wpftoolkit#1436]
Trying to add Zoombox in WPF application. 
When I add it on any Grid, it gives the following exception 
```
NullReferenceException: Object reference not set to an instance of an object.
StackTrace
at Xceed.Wpf.Toolkit.Zoombox.Zoombox.UpdateView(ZoomboxView view, Boolean allowAnimation, Boolean allowStackAddition, Int32 stackIndex)
   at Xceed.Wpf.Toolkit.Zoombox.Zoombox.ContentPresenterFirstArranged(Object sender, EventArgs e)
   at System.Windows.ContextLayoutManager.fireLayoutUpdateEvent()
   at System.Windows.ContextLayoutManager.UpdateLayout()
   at System.Windows.UIElement.UpdateLayout()
InnerException: None
```
XAML:
```
<xctk:Zoombox Content="Zoombox" HorizontalAlignment="Left" VerticalAlignment="Top"/>
```
Using Extended.Wpf.Toolkit version 3.4.0.
Can anyone help me out on this?
Thanks in advance.

**Comment by Dexter404** [comment]
Problem resolved. 
Thanks!
