### ISSUE TITLE
NullReferenceException in LayoutAnchorableFloatingWindowControl.OnInitialized

### ISSUE THREAD

**Issue by meyerrn** [xceedsoftware/wpftoolkit#1442]
Hello,
I migrated from 3.3 to 3.5, but now the application does not start anymore. Crash while loading (Deserialize) a layout. See Stack trace below. "_model" is null.  I think initialization is missing in constructor LayoutAnchorableFloatingWindowControl( LayoutAnchorableFloatingWindow model)

I skipped 3.4 because of another serious error.

System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Xceed.Wpf.AvalonDock
  StackTrace:
   at Xceed.Wpf.AvalonDock.Controls.LayoutAnchorableFloatingWindowControl.OnInitialized(EventArgs e)
   at System.Windows.FrameworkElement.TryFireInitialized()
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.PresentationSource.RootChanged(Visual oldRoot, Visual newRoot)
   at System.Windows.Interop.HwndSource.set_RootVisualInternal(Visual value)
   at System.Windows.Window.SetRootVisual()
   at System.Windows.Window.SetRootVisualAndUpdateSTC()
   at System.Windows.Window.SetupInitialState(Double requestedTop, Double requestedLeft, Double requestedWidth, Double requestedHeight)
   at System.Windows.Window.CreateSourceWindow(Boolean duringShow)
   at System.Windows.Window.ShowHelper(Object booleanBox)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at MyApp.App.Main()

**Comment by jmtuset** [comment]
I found the same problem. 

I make a litlle change in the constructor to hotfix. Change base -> this

internal LayoutDocumentFloatingWindowControl( LayoutDocumentFloatingWindow model )
        :**this**( model, false )
    {
    }

**Comment by Dirkster99** [comment]
It turns out that version 3.5 has the same critical issue in 2 different classes. The issue with the **NullReference Exception** shows when
- saving a layout with a **floating** tool window (NullReference Exception in LayoutAnchorableFloatingWindowControl) OR
- saving a layout with a **floating** document (NullReference Exception in LayoutDocumentFloatingWindowControl)

The correct fixes (see both references above) contain more than just setting the `_model` field since you are otherwise reloading a tool window layout without the abbility to close it later on (since the CloseCommand is not initialized if any of the fixes suggest here or [there](https://github.com/xceedsoftware/wpftoolkit/pull/1443) is applied).

**Comment by guy-avery** [comment]
Dirkster - I think your statement is correct, 

> The correct fixes (see both references above) contain more than just setting the _model field since you are otherwise reloading a tool window layout without the abbility to close it later on (since the CloseCommand is not initialized if any of the fixes suggest here or there is applied).

But jmtuset has the correct solution - you just need to call the other constructor - which will re-use the required initialisation code. Copying the same code between constructors in the same class is not good practice and usually indicates something is wrong with the design.

Hopefully the correct solution will be adopted but unless you have a very good reason not to,  I would recommend you update your solution to represent jmtuset solution.

**Comment by Dirkster99** [comment]
@guy-avery Thanks for pointing this out to me. You are right. The issue is in both cases the same and it can be solved with the same resolution as suggested by @jmtuset I've commit the correct solution and will it roll out to NuGet/Release Version with the next bug fix :-)

**Comment by guy-avery** [comment]
@Dirkster99 - that's great - thanks for the response.

**Comment by XceedBoucherS** [comment]
Hi,
This is already fixed in v3.6 (the next community edition to be released).
You can already try the latest v3.8 version for free for 45 days here : https://xceed.com/xceed-toolkit-plus-for-wpf/

**Comment by junrau** [comment]
Since this is a significant issue, can you re-list 3.4 on NuGet, so we can revert until the fixed code is released?

**Comment by sa-he** [comment]
Can't you please just create a release 3.5.1 or something, that includes this bugfix?

**Comment by Dirkster99** [comment]
I have created a version with a fix (and now you know why): https://github.com/Dirkster99/AvalonDock

**Comment by sa-he** [comment]
Great @Dirkster99 , do you also publish nuget packages for your repo?

**Comment by Dirkster99** [comment]
Yes, just click on one of the buttons in the **Readme.md** page:

![Untitled](https://user-images.githubusercontent.com/2129700/56971130-f99b8300-6b68-11e9-8e7c-9da4aedd78ae.png)


...and you shall the nuget package belonging to it:

So, clicking on the first **button (left cell from) AvalonDock** should, for example, get you here:
https://www.nuget.org/packages/Dirkster.AvalonDock

Also, be sure to scroll down the Readme.md to check out the list of other critical issues that have already been fixed in this release. And there is also Wiki page link at the bottom of the page that gives you a list of fixes that have been fixed in previous release (should you need any before 3.5).

Its still surprising to me how these discussions come back [time](https://github.com/xceedsoftware/wpftoolkit/issues/1445) and [again](https://github.com/xceedsoftware/wpftoolkit/issues/1381). And yet, [xceed claims to maintain the open source release](https://github.com/xceedsoftware/wpftoolkit/issues/1464#issuecomment-479009357) and people actually expect their problem to be fixed in a smaller time spane than 2 years ...

**Comment by sa-he** [comment]
Great job @Dirkster99 ! How can I use other usercontrols of the wpftoolkit and your version of AvalonDock at the same time? Do you have a different xml namespace to import?

**Comment by Dirkster99** [comment]
I am not sure how to answer this one as I am not in that situation and I did not change any namespaces since this would break existing applications for all other users (including myself).

But one way I could for using this mixed setup of:
- WpfToolkit + [Dirkster.AvalonDock](https://github.com/Dirkster99/AvalonDock)

would be to download both packages and manually include each part that you need in your project. Its not nice and definetely a hazzle, but since Xceed releases only twice a year it might be an OK effort compared to accepting that AvalonDock crashes your application (just because the user was using it as intended).

Maybe someone else in the comunity has a better idea but this is what I can come up with right now.

I wrote an article about lessons learned for designing and implementing [WPF control/theme libraries](https://www.codeproject.com/Articles/1236588/File-System-Controls-in-WPF-Version-III) because I noticed that (even in the 'real' opensource comunity) many authors tend to suck all kinds of functionality and dependencies into one huge product. The end of that is that you have huge follow up costs when you actually want to change from one product to another, or there are things that are very hard to do, like not using AvalonDock, but on the toolkit, or vice versa, or or or ...inflexibility and additional costs are definetely part of the equation just because someone wasn't to release more than one package ...this is the reason why I have so many control projects and even [MLib](https://github.com/Dirkster99/MLib) consists of more than one nuget package...

**Comment by sa-he** [comment]
If you fork the wpftoolkit repo, you have everything, not just AvalonDock and could therefor provide a nuget feature-equal package like "Extended.Wpf.Toolkit.Fixed". In case xceed some day decides to be accept pull requests, you could just integrate these changes into your fork.

Then, users could switch between "Extended.Wpf.Toolkit" and "Extended.Wpf.Toolkit.Fixed" as required.

**Comment by Dirkster99** [comment]
Yeah, this equation has just one little issue - which is that I am not interested in other parts of the Extended.Wpf.Toolkit and I am already maintaining 6 AvalonDock nuget packages as it is. So, you are asking me to add another 6th package (with way more lines of codes and controls) and also fix that for you because xceed won't do it? Well, I don't think I can do that time wise and since I am not being payed by xceed I am certainly not doing their work for something I don't need.

If someone else wants to contribute the other part of the toolkit I am open to suggestions...

**Comment by Dirkster99** [comment]
I recommend including the AvalonDock release binary builds from here:
https://ci.appveyor.com/project/Dirkster99/AvalonDock/build/artifacts

Ideally, there should be some form of build pipeline integration that goes over multiple projects to get a better handle on this one. I don't know of any but would be interested in contributing if someone can provide enough guidance ...usually there are plenty of cload services that are freely available for open source so I would be surprised if we could not get a CI integration over multiple projects publishing exactly the components we want to see in the resulting nugets...

**Comment by Dirkster99** [comment]
I recommend including the current binaries for AvalonDock from here:
https://ci.appveyor.com/project/Dirkster99/AvalonDock/build/artifacts

I am wondering if there is a free for open source cloud service pipeline we could use to merge results from multiple projects into one nuget, let me know if there is and whether there is something I can do about it...

**Comment by Dirkster99** [comment]
Looks like this thread is locked

**Comment by jogibear9988** [comment]
@sa-he I mange a fixed Version of WpfToolkit without Avalondock, see https://github.com/dotnetprojects/WpfExtendedToolkit
