### ISSUE TITLE
v3.8 causes a ParseException on manifest when using it in ClickOnce App during install

### ISSUE THREAD

**Issue by holyrav** [xceedsoftware/wpftoolkit#1562]
v3.8 causes a ParseException on manifest when using it in ClickOnce App during install.

Looking at the manifest, the only major change I spotted was that you included
"cs-CZ\Xceed.Wpf.AvalonDock.resources.dll"
Which for whatever reason seems to be a 1:1 copy of
"de\Xceed.Wpf.AvalonDock.resources.dll"

At least the same hash digest is indicated for these files is identical for both:
<hash>
        <dsig:Transforms>
          <dsig:Transform Algorithm="urn:schemas-microsoft-com:HashTransforms.Identity" />
        </dsig:Transforms>
        <dsig:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha256" />
        <dsig:DigestValue>slE2PtZIgiydsiTeWEwtuYMYfc/d510WP7RnLGqXXZU=</dsig:DigestValue>
</hash>

Workaround:
Excluding all language specific resource files from click once projects.

**Comment by XceedBoucherS** [comment]
Hi,
"cs-CZ\Xceed.Wpf.AvalonDock.resources.dll" and "de\Xceed.Wpf.AvalonDock.resources.dll" shouldn't be the same. One contains texts for czech while the other for deutsch.
But yes, the czech language was added in v3.8.
Where exactly did you install the files ? 
-Release tab on gitHub
-Code tab on gitHub
-Nuget
-Xceed web site
When exactly does the parsing exception occurs ?
What version of Windows are you using ?
Thank you.

**Comment by philwells** [comment]
I've run into the same issue. The files were installed from NuGet. The parsing exception occurs when either attempting to install or update the ClickOnce application. I'm using Windows 10 Enterprise version 1809.

Exception from the ClickOnce log was:

ERROR DETAILS
	Following errors were detected during this operation.
	* [2/5/2020 12:48:08 PM] System.Deployment.Application.InvalidDeploymentException (ManifestParse)
		- Exception reading manifest from file://[redacted].manifest: the manifest may not be valid or the file could not be opened.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.ManifestReader.FromDocument(String localPath, ManifestType manifestType, Uri sourceUri)
			at System.Deployment.Application.DownloadManager.DownloadApplicationManifest(AssemblyManifest deploymentManifest, String targetDir, Uri deploymentUri, IDownloadNotification notification, DownloadOptions options, Uri& appSourceUri, String& appManifestPath)
			at System.Deployment.Application.ApplicationActivator.DownloadApplication(SubscriptionState subState, ActivationDescription actDesc, Int64 transactionId, TempDirectory& downloadTemp)
			at System.Deployment.Application.ApplicationActivator.InstallApplication(SubscriptionState& subState, ActivationDescription actDesc)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl, Uri& deploymentUri)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
--- End of stack trace from previous location where exception was thrown ---
			at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)
		--- Inner Exception ---
		System.Deployment.Application.InvalidDeploymentException (ManifestParse)
		- Parsing and DOM creation of the manifest resulted in error. Following parsing errors were noticed: 
			-HRESULT: 	0x80070c81
			 Start line: 	0
			 Start column: 	0
			 Host file: 	
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.Manifest.AssemblyManifest.LoadCMSFromStream(Stream stream)
			at System.Deployment.Application.Manifest.AssemblyManifest..ctor(FileStream fileStream)
			at System.Deployment.Application.ManifestReader.FromDocument(String localPath, ManifestType manifestType, Uri sourceUri)
		--- Inner Exception ---
		System.Runtime.InteropServices.COMException
		- Exception from HRESULT: 0x80070C81
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Internal.Isolation.IsolationInterop.CreateCMSFromXml(Byte[] buffer, UInt32 bufferSize, IManifestParseErrorCallback Callback, Guid& riid)
			at System.Deployment.Application.Manifest.AssemblyManifest.LoadCMSFromStream(Stream stream)


The relevant entries from the manifest file were:

  <dependency>
    <dependentAssembly dependencyType="install" allowDelayedBinding="true" codebase="cs-CZ\Xceed.Wpf.AvalonDock.resources.dll" size="6144">
      <assemblyIdentity name="Xceed.Wpf.AvalonDock.resources" version="3.8.0.0" publicKeyToken="3E4669D2F30244F4" language="de" processorArchitecture="msil" />
      <hash>
        <dsig:Transforms>
          <dsig:Transform Algorithm="urn:schemas-microsoft-com:HashTransforms.Identity" />
        </dsig:Transforms>
        <dsig:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1" />
        <dsig:DigestValue>XLXw6NwqQza9a9pZmzQPsKcJGWg=</dsig:DigestValue>
      </hash>
    </dependentAssembly>
  </dependency>
  <dependency>
    <dependentAssembly dependencyType="install" allowDelayedBinding="true" codebase="de\Xceed.Wpf.AvalonDock.resources.dll" size="6144">
      <assemblyIdentity name="Xceed.Wpf.AvalonDock.resources" version="3.8.0.0" publicKeyToken="3E4669D2F30244F4" language="de" processorArchitecture="msil" />
      <hash>
        <dsig:Transforms>
          <dsig:Transform Algorithm="urn:schemas-microsoft-com:HashTransforms.Identity" />
        </dsig:Transforms>
        <dsig:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1" />
        <dsig:DigestValue>XLXw6NwqQza9a9pZmzQPsKcJGWg=</dsig:DigestValue>
      </hash>
    </dependentAssembly>
  </dependency>

**Comment by XceedBoucherS** [comment]
Hi,
What do you mean by the Click once app ?
Starting a new VS2019 project and installing the Toolkit v3.8 from Nuget, installs the Toolkit correctly with no manifest errors.

**Comment by philwells** [comment]
This is after the ClickOnce application has been built and deployed. The error shows up when the user double-clicks the ".application" file to install the application for the first time, or when the application subsequently attempts to update itself.

**Comment by XceedBoucherS** [comment]
Hi,
I know there is one ClickOnce app of the Toolkit available here : https://xceed.com/xceed-toolkit-plus-for-wpf/, but it's for the v4.0 version and it doesn't display any exception.
Where exactly do you click to install the "ClickOnce application" to build and install ? Where do you see the ".application" file ?
Thank you

**Comment by philwells** [comment]
The ClickOnce app I'm referring to is the application I have built for my users containing my business logic. This application uses the Toolkit (including it via NuGet).

**Comment by Groarhoarr** [comment]
Hi, I have the same problem. All is fine in Visual Studio, I can install and use the toolkit. After I published my app with Visual Studio (project property window -> Publish) to a file path, users can install it from this file path. But when users try to install or update my app, the manifest error message appears. Only with v3.8, v3.7 works fine.

**Comment by XceedBoucherS** [comment]
Oh yes...there is a typo.
The problem was only when getting the Toolkit from Nuget, not from GitHub.
It is now fixed. You can get it from Nuget. Please select package Toolkit v3.8.1, which is the same as v3.8.0, but with this fix.
Thank you for pointing this out.
