### ISSUE TITLE
LayoutContent  root null 

### ISSUE THREAD

**Issue by vikaschamp** [xceedsoftware/wpftoolkit#1709]
Hi , 

After docking multiple layout anchorable . It's root getting null exception .

at Xceed.Wpf.AvalonDock.Layout.LayoutContent.Float()
   at QTApplication.Classess.Clone_Helper.Initialize_Clones(String user_control_)
Object reference not set to an instance of an object.

Please suggest for this exception . Let me know for more information 
Thanks

**Comment by vikaschamp** [comment]
Hi @XceedBoucherS ,

I have created multiple user controls and bind with the layout anchorable and these anchorable are the children of layoutpanegroup . Every thing works fine . But when i dock the one floated layoutanchorable inside the others floated layout anchorable and i did same thing multiple time and when i am going to dock these layout acnhorable into the parent layoutpane group then it is not able to dock it's root getting null . The root panel of the layout root is getting null .

**Comment by XceedBoucherS** [comment]
Hi vikaschamp,
could you submit a sample code and the steps to reproduce the issue ? It would help to reproduce the exact same scenario. By reading text, it's easy to guess how the sample was made and how many time some LayoutAnchorables are floated and dropped.

Does this issue happens in the commercial version ? You can try it for free for 45 days here: https://xceed.com/en/our-products/product/toolkit-plus-for-wpf

Thank you
