### ISSUE TITLE
MessageBox ArgumentNullException

### ISSUE THREAD

**Issue by xceedsoftware** [xceedsoftware/wpftoolkit#29]
<b>brianlagunas[CodePlex]</b> <br />Hi, I'm getting an ArgumentNullException when using the new MessageBox. This is happening on a call to MessageBox.Show(). Strangely, this only happens if I hit a breakpoint before Show() is called.
nbsp
I have the calls to show encapsulated in a Module. Am I doing something wrong?
nbsp
Here is the StackTrace:
nbsp
Value cannot be null.
Parameter name: dependencyObject
nbsp
at System.Windows.Window.GetWindow(DependencyObject dependencyObject)
at Microsoft.Windows.Controls.MessageBox.CreateContainer()
at Microsoft.Windows.Controls.MessageBox.InitializeMessageBox(String text, String caption, MessageBoxButton button, MessageBoxImage image)
at Microsoft.Windows.Controls.MessageBox.ShowCore(String messageText, String caption, MessageBoxButton button, MessageBoxImage icon)
at Microsoft.Windows.Controls.MessageBox.Show(String messageText, String caption, MessageBoxButton button, MessageBoxImage icon)
at Reporting.Client.DataVaultCentre.Dialogs.MessageDialogs.Show(String messageText, MessageBoxImage icon) in C:\Dev\Reporting\Client\DataVaultCentre\Reporting.Client.DataVaultCentre\Utils\MessageDialogs.vb:line 14
at Reporting.Client.DataVaultCentre.Dialogs.MessageDialogs.ShowInformation(String messageText) in C:\Dev\Reporting\Client\DataVaultCentre\Reporting.Client.DataVaultCentre\Utils\MessageDialogs.vb:line 26
at Reporting.Client.DataVaultCentre.ViewModels.VaultItemViewModel.SaveDataGridCompleted(Object sender, RunWorkerCompletedEventArgs e) in C:\Dev\Reporting\Client\DataVaultCentre\Reporting.Client.DataVaultCentre\ViewModels\VaultItemViewModel.vb:line
468
at System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)
at System.ComponentModel.BackgroundWorker.AsyncOperationCompleted(Object arg)
at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
at System.Windows.Threading.DispatcherOperation.InvokeImpl()
at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
at System.Threading.ExecutionContext.runTryCode(Object userData)
at System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCleanup(TryCode code, CleanupCode backoutCode, Object userData)
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean ignoreSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
at System.Windows.Threading.DispatcherOperation.Invoke()
at System.Windows.Threading.Dispatcher.ProcessQueue()
at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Booleanamp handled)
at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Booleanamp handled)
at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
at System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSGamp msg)
at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
at System.Windows.Threading.Dispatcher.Run()
at System.Windows.Application.RunDispatcher(Object ignore)
at System.Windows.Application.RunInternal(Window window)
at System.Windows.Application.Run(Window window)
at System.Windows.Application.Run()
at Reporting.Client.DataVaultCentre.Application.Main() in C:\Dev\Reporting\Client\DataVaultCentre\Reporting.Client.DataVaultCentre\obj\x86\Debug\Application.g.vb:line 76
at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
at System.AppDomain.nExecuteAssembly(RuntimeAssembly assembly, String[] args)
at System.Runtime.Hosting.ManifestRunner.Run(Boolean checkAptModel)
at System.Runtime.Hosting.ManifestRunner.ExecuteAsAssembly()
at System.Runtime.Hosting.ApplicationActivator.CreateInstance(ActivationContext activationContext, String[] activationCustomData)
at System.Runtime.Hosting.ApplicationActivator.CreateInstance(ActivationContext activationContext)
at System.Activator.CreateInstance(ActivationContext activationContext)
at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssemblyDebugInZone()
at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean ignoreSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
at System.Threading.ThreadHelper.ThreadStart()

**Comment by xceedsoftware** [comment]
<b>brianlagunas[CodePlex]</b> <br />The reason it is showing behind your window is because you are showing the MessageBox before the parent window has loaded. therefore it has no parent. I am not sure how you are using the control, but make sure you are not calling the messagebox before
 the parent has fully loaded.

**Comment by xceedsoftware** [comment]
<b>CoderChris[CodePlex]</b> <br />Hi. Thanks for fixing this. It no longer crashes, however there is still a bit of an issue. If I hit a breakpoint before invoking the messagebox, the messagebox tends to pop up behind my application. I have two monitors and it also pops up on the monitor
 opposite to my application. Thanks.
