### ISSUE TITLE
System.NullReferenceException when put a RichTextBoxFormatBar in an WPF window

### ISSUE THREAD

**Issue by xceedsoftware** [xceedsoftware/wpftoolkit#338]
<b>ibraheemyan[CodePlex]</b> <br />Version: Extended WPF Toolkit - 1.6.0nbspnbspnbspSystem.NullReferenceExceptionObject reference not set to an instance of an object. at Xceed.Wpf.Toolkit.RichTextBoxFormatBar.UpdateItemCheckedState(ToggleButton button, DependencyProperty formattingProperty, Object
 expectedValue) at Xceed.Wpf.Toolkit.RichTextBoxFormatBar.UpdateToggleButtonState() at Xceed.Wpf.Toolkit.RichTextBoxFormatBar.UpdateVisualState() at Xceed.Wpf.Toolkit.RichTextBoxFormatBar.FormatToolbar_Loaded(Object sender, RoutedEventArgs e) at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object
 target, RoutedEventArgs routedEventArgs) at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised) at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args) at System.Windows.UIElement.RaiseEvent(RoutedEventArgs
 e) at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent) at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root) at MS.Internal.LoadedOrUnloadedOperation.DoWork() at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
 at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks() at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget) at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget) at
 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs) at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by xceedsoftware** [comment]
<b>BoucherS[CodePlex]</b> <br />Fixed in v2.0.
