### ISSUE TITLE
Avoid crash of old Winform property Editor

### ISSUE THREAD

**Issue by xceedsoftware** [xceedsoftware/wpftoolkit#467]
<b>EricOuellet[CodePlex]</b> <br />I pass an object designed for the WinForm propertyGrid and it crash. I modifed code to prevent the crash and wonder if it would be possible to add on try/catch ?

Proposed fix in PropertyGridUtilities::internal static FrameworkElement GetAttibuteEditor(PropertyItem propertyItem)
            // var instance = Activator.CreateInstance(type);
            // Replace previous line with next try/catch block to prevent crash of WinForm propertyEditor
            object instance = null;
            try
            {
                instance = Activator.CreateInstance(type);
            }
            catch (Exception ex)
            {
            }

**Comment by xceedsoftware** [comment]
<b>EricOuellet[CodePlex]</b> <br />Oups... I can't change the status. That's fine :-)
Thanks for the change.
Eric

**Comment by xceedsoftware** [comment]
<b>EricOuellet[CodePlex]</b> <br />It would be nice to have UITypeEditor supported but it is not major to me.
I have not verify the fix but I consider that it is done in V2. I will mark as done.


Thanks a lot.
Eric

**Comment by xceedsoftware** [comment]
<b>emartin[CodePlex]</b> <br />Fixed in v2.0

**Comment by xceedsoftware** [comment]
<b>EricOuellet[CodePlex]</b> <br />Sorry, i did not read comments in proper order... 
Please forget this and previous message.

**Comment by xceedsoftware** [comment]
<b>EricOuellet[CodePlex]</b> <br />The one provided is not ok ?

**Comment by xceedsoftware** [comment]
Yes, we should not assume any parameterless constructor on specified editor.



But actually,theeditor of typeUITypeEditor are not supported. Is this a feature that you would like to be working ? If it is the case, create a different issue request. We will fix that exception handling one and mark it as fixed.

**Comment by xceedsoftware** [comment]
<b>EricOuellet[CodePlex]</b> <br />Stack Trace 

at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean canBeCached, RuntimeMethodHandleInternal ctor, Boolean bNeedSecurityCheck)
at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark stackMark)
at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark stackMark)
at System.Activator.CreateInstance(Type type, Boolean nonPublic)
at System.Activator.CreateInstance(Type type)
at Xceed.Wpf.Toolkit.PropertyGrid.PropertyGridUtilities.GetAttibuteEditor(PropertyItem propertyItem) in c:\PRJ\IREQ\src\Community\WPFToolkit.Extended\PropertyGrid\Implementation\PropertyGridUtilities.cs:line 133


Message: No parameterless constructor defined for this object. 

I don't know how works property grid (old or new standards - if it ever changed). But the same code seems to work well with the old property grid. In fact I have both and both are fed the same way (they both receive the same selected object). I edit the failing
 selected object into the old property grid but Xceed see the exception because it also receive the selected object. The object is coming from National Instrument WinForm Control - ScatterPlot == ScatterPlotCollectionEditor.


This is my modification:
        if (editorAttribute != null)
        {
            Type type = Type.GetType(editorAttribute.EditorTypeName);

            // var instance = Activator.CreateInstance(type);
            // Replace previous line with next try/catch block to prevent crash of WinForm propertyEditor
            object instance = null;
            try
            {
                instance = Activator.CreateInstance(type);
            }
            catch (MissingMethodException ex)
            {
                Debug.Print(ex.Message);
            }

            if (instance != null  instance is ITypeEditor)
            {
                editor = (instance as ITypeEditor).ResolveEditor(propertyItem);
            }
        }

**Comment by xceedsoftware** [comment]
<b>emartin[CodePlex]</b> <br />Could you provide us with the stacktrace ?
