### ISSUE TITLE
NullReferenceException on Double property change followed by return

### ISSUE THREAD

**Issue by xceedsoftware** [xceedsoftware/wpftoolkit#488]
<b>jamesd77[CodePlex]</b> <br />If I change a double property value, then press return, I get a NullReferenceException. Stack trace: at Xceed.Wpf.Toolkit.PropertyGrid.PropertyGrid.OnPreviewKeyDown(KeyEventArgs e) at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object
 target) at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised) at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args) at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs
 args) at System.Windows.Input.InputManager.ProcessStagingArea() at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input) at System.Windows.Interop.HwndKeyboardInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawKeyboardActions
 actions, Int32 scanCode, Boolean isExtendedKey, Boolean isSystemKey, Int32 virtualKey) at System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSGamp msg, Booleanamp handled) at System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSGamp
 msg, ModifierKeys modifiers) at System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param) at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs) at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object
 source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler) at System.Windows.Threading.Dispatcher.WrappedInvoke(Delegate callback, Object args, Int32 numArgs, Delegate catchHandler) at System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherPriority
 priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs) at System.Windows.Interop.HwndSource.OnPreprocessMessageThunk(MSGamp msg, Booleanamp handled) at System.Windows.Interop.ComponentDispatcherThread.RaiseThreadMessage(MSGamp msg)
 at System.Windows.Threading.Dispatcher.TranslateAndDispatchMessage(MSGamp msg) at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame) at System.Windows.Application.RunInternal(Window window) at System.Windows.Application.Run() at SaabSecurity.OneView.ConfigurationTool.App.Main()
 in MyClass:line 0 at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args) at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly() at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback
 callback, Object state, Boolean ignoreSyncCtx) at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state) at System.Threading.ThreadHelper.ThreadStart()

**Comment by xceedsoftware** [comment]
<b>emartin[CodePlex]</b> <br />As a workaround wit the version 1.8, create yourself this sub class, it should work:


public class FixedPropertyGrid : PropertyGrid
{
protected override void OnPreviewKeyDown( KeyEventArgs e ){ //Do not call the base impementation }
} 

But the values will be updated only when the focus is lost, not on enter.

**Comment by xceedsoftware** [comment]
<b>emartin[CodePlex]</b> <br />Fixed in v1.9
