### ISSUE TITLE
Error: System.Net.WebException

### ISSUE THREAD

**Issue by xceedsoftware** [xceedsoftware/wpftoolkit#502]
<b>jgrindel[CodePlex]</b> <br />is there a new InstallSsisBatchDecoder.exe for SQL Server 2012? we are moving to 2012, and cannot build with version of Error: System.Net.WebException. started getting the below error message this morning.

[Geocode From Fields [331]] Error: System.Net.WebException: The remote server returned an error: (401) Unauthorized.
at System.Net.HttpWebRequest.GetResponse()
at SSISBatchGeocoder.Geocoder.ExecuteBingGeocodeFlow()
at SSISBatchGeocoder.Geocoder.ExecuteBatch()
at SSISBatchGeocoder.GeocoderTransformation.FlushCurrentBatch()
at SSISBatchGeocoder.GeocoderTransformation.ProcessInput(Int32 inputID, PipelineBuffer buffer)
at Microsoft.SqlServer.Dts.Pipeline.ManagedComponentHost.HostProcessInput(IDTSManagedComponentWrapper100 wrapper, Int32 inputID, IDTSBuffer100 pDTSBuffer, IntPtr bufferWirePacket)

**Comment by xceedsoftware** [comment]
Wrong project
