### ISSUE TITLE
Databinding issue in InputBase for the Designer

### ISSUE THREAD

**Issue by xceedsoftware** [xceedsoftware/wpftoolkit#53]
<b>CStroliaDavis[CodePlex]</b> <br />Impressive toolbox. I like it quite a bit so far. 
nbsp
I was attempting to use the MaskedTextBox. All seems fine until I attempt to include databinding. Then it gives me an error in the designer. I'm not finished with the app I'm working on, but it seems to work okay in the executable.
nbsp
Here is the simplest code I could use to produce the error in my project. 
lttk:MaskedTextBox Name=quotphoneTextBoxquot Text=quot{Binding Path=Phone}quot Mask=quot(###) ###-####quot/gt
nbsp
Here is the error that appears in the Designer when binding is attempted:
nbsp
System.Reflection.TargetInvocationException
Exception has been thrown by the target of an invocation.
at System.RuntimeMethodHandle._InvokeMethodFast(IRuntimeMethodInfo method, Object target, Object[] arguments, SignatureStructamp sig, MethodAttributes methodAttributes, RuntimeType typeOwner)
at System.RuntimeMethodHandle.InvokeMethodFast(IRuntimeMethodInfo method, Object target, Object[] arguments, Signature sig, MethodAttributes methodAttributes, RuntimeType typeOwner)
at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture, Boolean skipVisibilityChecks)
at System.Delegate.DynamicInvokeImpl(Object[] args)
at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
nbsp

System.NullReferenceException
Object reference not set to an instance of an object.
at Microsoft.Windows.Controls.Primitives.InputBase.SyncTextAndValueProperties(DependencyProperty p, Object newValue) in C:\Users\strolcx\Desktop\ExtendedWPFToolkitSolution\Src\WPFToolkit.Extended\Core\Primitives\InputBase.cs:line 168
at Microsoft.Windows.Controls.Primitives.InputBase.OnTextPropertyChanged(DependencyObject d, DependencyPropertyChangedEventArgs e) in C:\Users\strolcx\Desktop\ExtendedWPFToolkitSolution\Src\WPFToolkit.Extended\Core\Primitives\InputBase.cs:line 48
at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntryamp newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue,
 OperationType operationType)
at System.Windows.DependencyObject.InvalidateProperty(DependencyProperty dp)
at System.Windows.Data.BindingExpressionBase.Invalidate(Boolean isASubPropertyChange)
at System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
at System.Windows.Data.BindingExpression.Activate(Object item)
at System.Windows.Data.BindingExpression.AttachToContext(AttachAttempt attempt)
at System.Windows.Data.BindingExpression.MS.Internal.Data.IDataBindEngineClient.AttachToContext(Boolean lastChance)
at MS.Internal.Data.DataBindEngine.Task.Run(Boolean lastChance)
at MS.Internal.Data.DataBindEngine.Run(Object arg)
at MS.Internal.Data.DataBindEngine.OnLayoutUpdated(Object sender, EventArgs e)
at System.Windows.ContextLayoutManager.fireLayoutUpdateEvent()
at System.Windows.ContextLayoutManager.UpdateLayout()
at System.Windows.UIElement.UpdateLayout()
at System.Windows.Interop.HwndSource.SetLayoutSize()
at System.Windows.Interop.HwndSource.set_RootVisualInternal(Visual value)
at System.Windows.Interop.HwndSource.set_RootVisual(Visual value)
at MS.Internal.DeferredHwndSource.ProcessQueue(Object sender, EventArgs e)

**Comment by xceedsoftware** [comment]
<b>brianlagunas[CodePlex]</b> <br />What version are you using? Does this occur in Blend or Visual Studio? I am unable to duplicate this in v1.3.

**Comment by xceedsoftware** [comment]
<b>brianlagunas[CodePlex]</b> <br />Just for fun try defining the Mask before the Text and see if that will fix the issue. So change it to tk:MaskedTextBox Name=phoneTextBox Mask=(###) ###-#### Text={Binding Path=Phone} /
