### ISSUE TITLE
CollectionControl.PersistChanges exception

### ISSUE THREAD

**Issue by xceedsoftware** [xceedsoftware/wpftoolkit#670]
<b>ruderik[CodePlex]</b> <br />Hi,

I have a nested structure of classes assigned to a PropertyGrid.
When i edit a collection field, the collection editor opens, fine.
Now when i change a (string) value in the collection editor and press the OK button an exception is thrown, from the code below.

The exception
2013-09-20 08:48:33,348 [9] FATAL Twister.App - CurrentDomain_UnhandledException - Unhandled exception : System.NotSupportedException: Collection was of a fixed size.
at System.Array.System.Collections.IList.Add(Object value)
at Xceed.Wpf.Toolkit.CollectionControl.PersistChanges()

The code where it is thrown
CollectionControl.c
public void PersistChanges()
{
  IList list = ComputeItemsSource();
  if( list == null )
    return;

  //the easiest way to persist changes to the source is to just clear the source list and then add all items to it.
  list.Clear();

  foreach( var item in Items )
  {
    list.Add( item );     lt-------------------------- EXCEPTION
  }
}

My data structure looks like this

// VectorType --- Data(list/collection of DataType)
// --- ID (string)

// DataType --- class(ExpectedKeywordSectionType)
// --- class(InputKeywordSectionType)
// --- Objective (string)

An VectorType instance is assigned to the SelectedObject of my PropertyGrid, and i'm trying to edit the Objective (in the collectioneditor)
In the debugger i saw that the 'list' object has property 'IsFixedSize = true', maybe a check should be added here?

But what is more important for me; how could i prevent this from happening? Is it my data structure that is not supported or is there a workaround for this?

Attached is a debugger screenshot with relevant values just before the point the exception is thrown.

Thanks in advance,

Ruud

**Comment by xceedsoftware** [comment]
<b>ruderik[CodePlex]</b> <br />Hi, 

Thanks for the workaround! And the future fix. 

Regards,
Ruud

**Comment by xceedsoftware** [comment]
<b>BoucherS[CodePlex]</b> <br />Hi, 

Here's a workaround.
You can add a check for an array type and fill the list array item by item.
In CollectionControl.PersistChanges(), just replace 
foreach( var item in Items )
{
     list.Add( item );
 }
with
if( list.GetType().BaseType == typeof( System.Array ) )
{
    for( int i = 0; i  Items.Count; ++i )
       list[ i ] = Items[ i ];
}
else
{
    foreach( var item in Items )
    {
       list.Add( item );
     }
 }
This problem will be fixed in v2.1.

**Comment by xceedsoftware** [comment]
<b>ruderik[CodePlex]</b> <br />Hi, 

Thanks for the answer.
The object i'm assigning to the PropertyGrid is constructed with deserialization of XML. So i constructed classes from the belonging XSD and use those types to deserialize the XML.
If you like i can put some code here (it takes some effort off course), but i don't do anything out of the ordinary.

Allthough the array is data-bound to a treeview, maybe that is the problem? 

Thanks,
Ruud

**Comment by xceedsoftware** [comment]
<b>BoucherS[CodePlex]</b> <br />Hi, 

the problem comes from the list being of a fixed size. When the list is not fixed, it works well.
How did you get a fixedSize list ? Can you paste a code snippet ? 

Based on this site : 
http://msdn.microsoft.com/en-us/library/bb354714%28v=vs.100%29.aspx 
fixedSize list does not allow the addition or removal of elements. But you were able to clear to list before the exception was thrown during addition !


I believe a check for the fixedsize property would be a good idea and then just modify the listitems would fix the problem.
