### ISSUE TITLE
SplitButton - Exception on "ESC" key

### ISSUE THREAD

**Issue by xceedsoftware** [xceedsoftware/wpftoolkit#717]
<b>marcloc[CodePlex]</b> <br />While the DropDown Popup is open, if i press quotESCquot key, i the Exception is thrown:

System.Transactions Critical: 0 : ltTraceRecord xmlns=quothttp://schemas.microsoft.com/2004/10/E2ETraceEvent/TraceRecordquot Severity=quotCriticalquotgtltTraceIdentifiergthttp://msdn.microsoft.com/TraceCodes/System/ActivityTracing/2004/07/Reliability/Exception/Unhandledlt/TraceIdentifiergtltDescriptiongtUnhandled
 exceptionlt/DescriptiongtltAppDomaingtMB.Client.Shell.vshost.exelt/AppDomaingtltExceptiongtltExceptionTypegtSystem.NullReferenceException, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089lt/ExceptionTypegtltMessagegtObject
 reference not set to an instance of an object.lt/MessagegtltStackTracegt at Xceed.Wpf.Toolkit.DropDownButton.CloseDropDown(Boolean isFocusOnButton)
at Xceed.Wpf.Toolkit.DropDownButton.OnKeyDown(Object sender, KeyEventArgs e)
at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
at System.Windows.Input.InputManager.ProcessStagingArea()
at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
at System.Windows.Interop.HwndKeyboardInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawKeyboardActions actions, Int32 scanCode, Boolean isExtendedKey, Boolean isSystemKey, Int32 virtualKey)
at System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSGampamp; msg, Booleanampamp; handled)
at System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSGampamp; msg, ModifierKeys modifiers)
at System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
at System.Windows.Threading.Dispatcher.Invoke(DispatcherPriority priority, Delegate method, Object arg)
at System.Windows.Interop.HwndSource.OnPreprocessMessageThunk(MSGampamp; msg, Booleanampamp; handled)
at System.Windows.Interop.ThreadMessageEventHandler.Invoke(MSGampamp; msg, Booleanampamp; handled)
at System.Windows.Interop.ComponentDispatcherThread.RaiseThreadMessage(MSGampamp; msg)
at System.Windows.Threading.Dispatcher.TranslateAndDispatchMessage(MSGampamp; msg)
at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
at System.Windows.Application.RunInternal(Window window)
at System.Windows.Application.Run()
at MB.Client.Shell.App.Main() in c:\Projects\MB2\Sources\Client\Shell\obj\x86\Debug\App.g.cs:line 0
at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
at System.Threading.ThreadHelper.ThreadStart()lt/StackTracegtltExceptionStringgtSystem.NullReferenceException: Object reference not set to an instance of an object.
at Xceed.Wpf.Toolkit.DropDownButton.CloseDropDown(Boolean isFocusOnButton)
at Xceed.Wpf.Toolkit.DropDownButton.OnKeyDown(Object sender, KeyEventArgs e)
at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
at System.Windows.Input.InputManager.ProcessStagingArea()
at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
at System.Windows.Interop.HwndKeyboardInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawKeyboardActions actions, Int32 scanCode, Boolean isExtendedKey, Boolean isSystemKey, Int32 virtualKey)
at System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSGampamp; msg, Booleanampamp; handled)
at System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSGampamp; msg, ModifierKeys modifiers)
at System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
at System.Windows.Threading.Dispatcher.Invoke(DispatcherPriority priority, Delegate method, Object arg)
at System.Windows.Interop.HwndSource.OnPreprocessMessageThunk(MSGampamp; msg, Booleanampamp; handled)
at System.Windows.Interop.ThreadMessageEventHandler.Invoke(MSGampamp; msg, Booleanampamp; handled)
at System.Windows.Interop.ComponentDispatcherThread.RaiseThreadMessage(MSGampamp; msg)
at System.Windows.Threading.Dispatcher.TranslateAndDispatchMessage(MSGampamp; msg)
at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
at System.Windows.Application.RunInternal(Window window)
at System.Windows.Application.Run()
at MB.Client.Shell.App.Main() in c:\Projects\MB2\Sources\Client\Shell\obj\x86\Debug\App.g.cs:line 0
at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
at System.Threading.ThreadHelper.ThreadStart()lt/ExceptionStringgtltDataItemsgtltDatagtlt/Datagtlt/DataItemsgtlt/Exceptiongtlt/TraceRecordgt

**Comment by xceedsoftware** [comment]
<b>BoucherS[CodePlex]</b> <br />Hi,
I can't reproduce the exception. What exactly is in the popup ? Can you provide a code snippet ?
