### ISSUE TITLE
MessageBox Exception in Xceed but not in WinForms.

### ISSUE THREAD

**Issue by xceedsoftware** [xceedsoftware/wpftoolkit#792]
<b>Tintenfiisch[CodePlex]</b> <br />Hello all,

first I have to say thank you for this toolkit ! It is awesome !!

I have found an issue when I wanted to replace the MessageBox of WinForms with the Xceed Message Box.

I am starting with MessageBox.Show(...) a message box from an STA background thread. If I use the WinForms MessageBox everything works OK.

But if I just replace the reference to System.Windows.Forms with the reference to Xceed, I get following Exception when calling MessageBox.Show(...):
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---gt System.InvalidOperationException: The calling thread cannot access this object because a different thread owns it.
   at System.Windows.Threading.Dispatcher.VerifyAccess()
   at System.Windows.Threading.DispatcherObject.VerifyAccess()
   at System.Windows.Application.get_Windows()
   at Xceed.Wpf.Toolkit.MessageBox.ComputeOwnerWindow()
   at Xceed.Wpf.Toolkit.MessageBox.CreateContainer()
   at Xceed.Wpf.Toolkit.MessageBox.ShowDialog()
   at Xceed.Wpf.Toolkit.MessageBox.ShowCore(Window owner, String messageText, String caption, MessageBoxButton button, MessageBoxImage icon, MessageBoxResult defaultResult, Style messageBoxStyle)
   at Xceed.Wpf.Toolkit.MessageBox.Show(String messageText, String caption, MessageBoxButton button, Style messageBoxStyle)
   at Xceed.Wpf.Toolkit.MessageBox.Show(String messageText)
In general I know what the exception is about (Dispatcher, etc...) but I wanted to ask if this behavior is expected by your developers or are you planning to change the behavior in future.

It would be nice if it will be fixed in the future that people just easily exchange their old implementation and not having to concern about the dispatcher.

Thank you all in advance !!

**Comment by xceedsoftware** [comment]
<b>BoucherS[CodePlex]</b> <br />Hi, 

v2.2.1 is currently available to community and v2.3.1 for the Plus users.
The next release should come out shortly is v2.3.1 for community and v2.4 (with the fix) for the Plus users.


Plus users are always 1 version ahead, 
https://wpftoolkit.codeplex.com/wikipage?title=Compare%20Editions

**Comment by xceedsoftware** [comment]
<b>csharpuser[CodePlex]</b> <br />And when will version 2.4 come out? Also, is there a work around? 

Thanks,

**Comment by xceedsoftware** [comment]
<b>BoucherS[CodePlex]</b> <br />Hi, 

This will be fixed in v2.4.

**Comment by xceedsoftware** [comment]
<b>Tintenfiisch[CodePlex]</b> <br />Hi, 

here is an example: 

First code is using XCeed and is producing the exception: 
        void button3_Click(object sender, RoutedEventArgs e)
        {
            Thread t = new Thread(ShowBoxWithException);
            t.ApartmentState = ApartmentState.STA;
            t.Start();
        }
        
        /// summary
        /// Calling Xceed wpf message box produces the exception
        /// /summary
        void ShowBoxWithException()
        {
            Xceed.Wpf.Toolkit.MessageBox.Show(Hello);
        }
Second code is using System.Windows and is behaving correctly:
        void button4_Click(object sender, RoutedEventArgs e)
        {
            Thread t = new Thread(ShowBoxWithoutException);
            t.ApartmentState = ApartmentState.STA;
            t.Start();
        }
        
        /// summary
        /// Calling System.Windows. Message box is behaving correctly
        /// /summary
        void ShowBoxWithoutException()
        {
            System.Windows.MessageBox.Show(Hello);
        }
Thank you in advance !

**Comment by xceedsoftware** [comment]
<b>BoucherS[CodePlex]</b> <br />Hi, 

Can you provide a small sample with the exception ?
Thanks. 

You don't need to use a WindowContainer to use the MessageBox, but it is a better way of doing things. It will control modal windows.

**Comment by xceedsoftware** [comment]
<b>csharpuser[CodePlex]</b> <br />Any progress on this issue? I have the same problem. I would like to replace all Windows MessageBox with Xceed messagebox. The documentation is sparse, but it almost looks like each time you want to use the XCeed MessageBox, you need to use a WindowContainer.


Thanks
