### ISSUE TITLE
PropertyGrid issue with ValueRangeTextBox

### ISSUE THREAD

**Issue by xceedsoftware** [xceedsoftware/wpftoolkit#877]
<b>junrau[CodePlex]</b> <br />I am loading an object into the PropertyGrid, and I get the below error. I use the PropertyGrid for many other types, and just one type causes this exception. Doesn't the PropertyGrid only create textboxes for types that it can handle? Is there a way to
 find out which property/value is causing the exception?

InnerException: System.InvalidCastException
   _HResult=-2147467262
   _message=Object must implement IConvertible.
   HResult=-2147467262
   IsTransient=false
   Message=Object must implement IConvertible.
   Source=mscorlib
   StackTrace:
        at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
        at Xceed.Wpf.Toolkit.Primitives.ValueRangeTextBox.ValueCoerceValueCallback(Object sender, Object value)
        at System.Windows.DependencyObject.ProcessCoerceValue(DependencyProperty dp, PropertyMetadata metadata, EntryIndexamp entryIndex, Int32amp targetIndex, EffectiveValueEntryamp newEntry, EffectiveValueEntryamp oldEntry, Objectamp oldValue, Object baseValue, Object controlValue, CoerceValueCallback coerceValueCallback, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, Boolean skipBaseValueChecks)
        at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntryamp newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
        at System.Windows.DependencyObject.CoerceValue(DependencyProperty dp)
        at Xceed.Wpf.Toolkit.Primitives.ValueRangeTextBox.OnInitialized(EventArgs e)
   InnerException:

**Comment by xceedsoftware** [comment]
<b>BoucherS[CodePlex]</b> <br />Hi, 

Thanks for clarifying this issue. 
It will be fixed in v2.7.
In the meantime, you can go in file Xceed.Wpf.Toolkit/Primitives/ValueRangetextBox,
In method : object ConvertValueToDataType( object value, Type type )
Replace 
System.Convert.ChangeType...
by 
ChangeTypeHelper.ChangeType...

**Comment by xceedsoftware** [comment]
<b>junrau[CodePlex]</b> <br />This example produces the exception. 

XAML: 

Button Content=Go Click=GuidGoButton_Click /
wpfPg:PropertyGrid Name=testPropertyGrid / 

Code: 

private void GuidGoButton_Click(object sender, RoutedEventArgs e)
{
var o = new GuidTest()
{
    GuidProp = Guid.NewGuid()
};

this.testPropertyGrid.SelectedObject = o;
} 

private class GuidTest
{
public Guid? GuidProp { get; set; }
}

**Comment by xceedsoftware** [comment]
<b>junrau[CodePlex]</b> <br />I have distilled this down to only happening when the PropertyGrid's SelectedObject is an object with a property of type Guid?, and it has a value.

**Comment by xceedsoftware** [comment]
<b>BoucherS[CodePlex]</b> <br />Hi, 

Can you attach a sample showing the problem so we can reproduce to test?
Thanks.
