### ISSUE TITLE
'Initialization of 'Xceed.Wpf.Toolkit.RangeSlider' threw an exception in VS2015 CTP6

### ISSUE THREAD

**Issue by xceedsoftware** [xceedsoftware/wpftoolkit#889]
<b>AntoniDol[CodePlex]</b> <br />Since installation of Visual Studion 2015 CTP6 RangeSlider gives as runtime error:

{quot'Initialization of 'Xceed.Wpf.Toolkit.RangeSlider' threw an exception.' Line number '87' and line position '189'.quot}

{pack://application:,,,/Coolblue.Purchasing.CompetitorPricing;component/views/elasticitysettingsview.xaml}

{quotInitialization of 'Xceed.Wpf.Toolkit.Core.VersionResourceDictionary' threw an exception.quot}

{quotCannot locate resource 'xceed.wpf.toolkit;v2.3.0.0;themes/xceed.wpf.toolkit;v2.3.0.0;component/themes/aero/brushes_normalcolor.xaml'.quot}

This did not happen before in Visual Studio 2015 Preview.

Dit something change in VS2015 CTP6 that broke this?

Thanks in Advance for any answers,
Antoni Dol

**Comment by xceedsoftware** [comment]
<b>matovich[CodePlex]</b> <br />Yes thanks, we were on 2.4 and I didn't realize that. I pulled down the code to change and found the change already in place and then looked farther and saw our version. All the comments in this list were saying next version and the issue is
 still active at this point so I was taking that as it hadn't been fixed yet.

I was planning to get on this morning and say that 2.5 fixed it so folks would know they just need to update their version.


Thanks

**Comment by xceedsoftware** [comment]
<b>mayerwin[CodePlex]</b> <br />Version 2.5 works fine here with both the RC and now non RC version of Visual Studio 2015. Maybe you are having another problem.

**Comment by xceedsoftware** [comment]
<b>matovich[CodePlex]</b> <br />Yep, new shinny version of Visual Studio with lots of great new WPF options in debug but can't use any of them in our project because we have the wpf toolkit and need to wait for the next version.

Any idea on the schedule? 

Guess we will recompile the source for now

**Comment by xceedsoftware** [comment]
<b>tiesmaster[CodePlex]</b> <br />This is still a problem in the now non-RC version of 2015, even with the v2.5. Do you guys plan to release a new version soon?

**Comment by xceedsoftware** [comment]
<b>mayerwin[CodePlex]</b> <br />Thanks. In the meantime I was able to recompile the source with your suggested modification and it works.

**Comment by xceedsoftware** [comment]
<b>BoucherS[CodePlex]</b> <br />Hi, 

it will be included in the next Community version of the Toolkit.

**Comment by xceedsoftware** [comment]
<b>mayerwin[CodePlex]</b> <br />Same issue here with all WPF Toolkit controls. 
When can we expect this critical bug to be fixed in the Community Edition (I guess it wouldn't make sense to artificially delay it)?

**Comment by xceedsoftware** [comment]
<b>AlexeiShcherbakov[CodePlex]</b> <br />I have reported about it 2 weeks ago 
https://connect.microsoft.com/VisualStudio/feedback/details/1329814

**Comment by xceedsoftware** [comment]
<b>BoucherS[CodePlex]</b> <br />Thank you for testing. This is an issue related to VS2015 with a Windows different from Windows 8. It will be fixed in v2.8.

**Comment by xceedsoftware** [comment]
<b>JeremyBake[CodePlex]</b> <br />THANK YOU. BusyIndicator throws the same exception in VS 2015 RC Professional. This fixed it.
There should be some kind of sticky up front for this until it works out of the box.

**Comment by xceedsoftware** [comment]
<b>BoucherS[CodePlex]</b> <br />Hi, 

Go in file Xceed.Wpf.Toolkit/Core/VersionResourceDictionary.cs
In method ISupportInitialize.EndInit()
Replace :
string uriStr = string.Format( @{0};v{1};component/{2}, this.AssemblyName, _XceedVersionInfo.Version, this.SourcePath );
this.Source = new Uri( uriStr, UriKind.Relative );
with :
string uriStr = string.Format( @pack://application:,,,/{0};v{1};component/{2}, this.AssemblyName, _XceedVersionInfo.Version, this.SourcePath );
this.Source = new Uri( uriStr, UriKind.Absolute );
and see if you still ahev the exception.

**Comment by xceedsoftware** [comment]
<b>CFI[CodePlex]</b> <br />As I had the same problem I just tested your example and I get the same exception there!
Only difference I can see: We use Windows 7 here...
I'll test it using Win 8.1 at home later.

**Comment by xceedsoftware** [comment]
<b>BoucherS[CodePlex]</b> <br />Hi, 

I just tried the following sample :
StackPanel
      xctk:IntegerUpDown Value=35 /
      xctk:ColorPicker SelectedColor=Blue/
      xctk:RangeSlider Minimum=0 Maximum=100/
      xctk:WatermarkTextBox Watermark=Testing/
/StackPanel
and it worked without any exceptions. 
Here are the setting I used :
-Windows 8.1
-VisualStudio 2015 RC , Version 14.0.22823.1 D14REL
-Target Framework : .NET Framework 4.6 (.NET Framework 4.5.2 also worked)
-Xceed.Wpf.Toolkit v2.4.

**Comment by xceedsoftware** [comment]
<b>Jazzman82[CodePlex]</b> <br />Same here with v2.4.0 and VS 2015 Professional RC and ColorPicker....

**Comment by xceedsoftware** [comment]
<b>mBerghauser[CodePlex]</b> <br />Still appears to be happening on VS2015 Community Edition RC. In my case it occurs with the use of the IntegerUpDown control. Full exception as follows:


System.Windows.Markup.XamlParseException: 'Initialization of 'Xceed.Wpf.Toolkit.IntegerUpDown' threw an exception.' Line number '183' and line position '57'. --- System.Xaml.XamlObjectWriterException: Initialization of 'Xceed.Wpf.Toolkit.Core.VersionResourceDictionary'
 threw an exception. --- System.IO.IOException: Cannot locate resource 'xceed.wpf.toolkit;v2.3.0.0;themes/xceed.wpf.toolkit;v2.3.0.0;component/themes/aero/brushes_normalcolor.xaml'.
at MS.Internal.AppModel.ResourcePart.GetStreamCore(FileMode mode, FileAccess access)
at System.IO.Packaging.PackagePart.GetStream(FileMode mode, FileAccess access)
at System.IO.Packaging.PackWebResponse.CachedResponse.GetResponseStream()
at System.IO.Packaging.PackWebResponse.GetResponseStream()
at System.IO.Packaging.PackWebResponse.get_ContentType()
at MS.Internal.WpfWebRequestHelper.GetContentType(WebResponse response)
at MS.Internal.WpfWebRequestHelper.GetResponseStream(WebRequest request, ContentType contentType)
at System.Windows.ResourceDictionary.set_Source(Uri value)
at Xceed.Wpf.Toolkit.Core.VersionResourceDictionary.System.ComponentModel.ISupportInitialize.EndInit()
at MS.Internal.Xaml.Runtime.ClrObjectRuntime.InitializationGuard(XamlType xamlType, Object obj, Boolean begin)
--- End of inner exception stack trace ---
at MS.Internal.Xaml.Runtime.ClrObjectRuntime.InitializationGuard(XamlType xamlType, Object obj, Boolean begin)
at MS.Internal.Xaml.Runtime.PartialTrustTolerantRuntime.InitializationGuard(XamlType xamlType, Object obj, Boolean begin)
at System.Xaml.XamlObjectWriter.Logic_EndInit(ObjectWriterContext ctx)
at System.Xaml.XamlObjectWriter.WriteEndObject()
at System.Xaml.XamlWriter.WriteNode(XamlReader reader)
at System.Xaml.XamlServices.Transform(XamlReader xamlReader, XamlWriter xamlWriter, Boolean closeWriter)
at System.Xaml.XamlServices.Transform(XamlReader xamlReader, XamlWriter xamlWriter)
at System.Windows.SystemResources.ResourceDictionaries.LoadDictionary(Assembly assembly, String assemblyName, String resourceName, Boolean isTraceEnabled)
at System.Windows.SystemResources.ResourceDictionaries.LoadThemedDictionary(Boolean isTraceEnabled)
at System.Windows.SystemResources.FindDictionaryResource(Object key, Type typeKey, ResourceKey resourceKey, Boolean isTraceEnabled, Boolean allowDeferredResourceReference, Boolean mustReturnDeferredResourceReference, Boolean canCache)
at System.Windows.SystemResources.FindResourceInternal(Object key, Boolean allowDeferredResourceReference, Boolean mustReturnDeferredResourceReference)
at System.Windows.StyleHelper.GetThemeStyle(FrameworkElement fe, FrameworkContentElement fce)
at System.Windows.FrameworkElement.UpdateThemeStyleProperty()
at System.Windows.FrameworkElement.OnInitialized(EventArgs e)
at Xceed.Wpf.Toolkit.Primitives.UpDownBase`1.OnInitialized(EventArgs e)
at System.Windows.FrameworkElement.TryFireInitialized()
at System.Windows.FrameworkElement.EndInit()
at MS.Internal.Xaml.Runtime.ClrObjectRuntime.InitializationGuard(XamlType xamlType, Object obj, Boolean begin)
--- End of inner exception stack trace ---
at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)

**Comment by xceedsoftware** [comment]
<b>vibhoretanwer[CodePlex]</b> <br />Is there any workaround for this till next stable version comes out?

**Comment by xceedsoftware** [comment]
<b>AntoniDol[CodePlex]</b> <br />That really helps, thank you! 

You might consider researching the issue as one the might occur when VS2015 goes live.
Visual Studio 2015 programmers might consider pondering about why this issue occurs in the first place.

**Comment by xceedsoftware** [comment]
<b>BoucherS[CodePlex]</b> <br />Hi, 

VS2015 CTP6 is not a release version of Visual Studio. I suggest waiting for a final, bug free, release.


Visual Studio 2015 CTPs are for testing and feedback purposes only. This release is unsupported and are not intended for use on production computers, or to create production code. We strongly recommend only installing this release in a virtual machine,
 or on a computer that is available for reformatting.

**Comment by xceedsoftware** [comment]
<b>jnothstine[CodePlex]</b> <br />Same problem here. Now my application won't run and I am stuck. How doe we get around this problem?

**Comment by xceedsoftware** [comment]
<b>killnine[CodePlex]</b> <br />Same thing happening for me, except with WatermarkTexBox. 

Not sure what else to do, as this works fine on VS2013 SP4.
