### ISSUE TITLE
AvalonDock Invalid Window Handle Exception on switching Windows Theme

### ISSUE THREAD

**Issue by xceedsoftware** [xceedsoftware/wpftoolkit#897]
<b>AndreyLezhnev[CodePlex]</b> <br />I'm using the AvalonDock for a project. When working with my application on remote desktop I have encountered an error. When I'm connectin to station remotely it seems that windows theme on remote desktop is changing and the AvalonDoc application on remote
 station is failing with the invalid handle exception. 
It is possible to reproduce the fail without remoted desktop. Switching back to windows classic theme on Windows 7 caused an unhandled quotInvalid window handle exceptionquot. To reproduce it you have to drag out one of the LayoutAnchorable item (for example
 the Toolbox) to float, then start switching back and forth between the classic Windows theme and an aero theme (sometimes it happens for the first theme change).

Program Location:
at MS.Win32.HwndWrapper.DestroyWindow(Object args)
at MS.Win32.HwndWrapper.Dispose(Boolean disposing, Boolean isHwndBeingDestroyed)
at MS.Win32.HwndWrapper.Dispose()
at System.Windows.Interop.HwndSource.Dispose(Boolean disposing)
at System.Windows.Interop.HwndSource.Dispose()
at Xceed.Wpf.AvalonDock.Controls.LayoutFloatingWindowControl.OnUnloaded(Object sender, RoutedEventArgs e)
at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
at System.Windows.BroadcastEventHelper.BroadcastUnloadedEvent(Object root)
at MS.Internal.LoadedOrUnloadedOperation.DoWork()
at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
at System.Windows.Threading.DispatcherOperation.InvokeImpl()
at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
at System.Windows.Threading.DispatcherOperation.Invoke()
at System.Windows.Threading.Dispatcher.ProcessQueue()
at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Booleanamp handled)
at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Booleanamp handled)
at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSGamp msg)
at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
at System.Windows.Threading.Dispatcher.Run()
at System.Windows.Application.RunDispatcher(Object ignore)
at System.Windows.Application.RunInternal(Window window)
at System.Windows.Application.Run(Window window)
at System.Windows.Application.Run()

**Comment by xceedsoftware** [comment]
<b>AndreyLezhnev[CodePlex]</b> <br />Hi James,
Actually I'm out of the project where we used the Avalon, but I'll try to ask guys to check this out.
Regards,
Andrey

**Comment by xceedsoftware** [comment]
<b>jameslewisbush[CodePlex]</b> <br />Hi, I am still seeing this issue using Toolkit v.2.8. Can you confirm it has been resolved?


Thanks,
James

**Comment by xceedsoftware** [comment]
<b>AndreyLezhnev[CodePlex]</b> <br />Thank you.

**Comment by xceedsoftware** [comment]
<b>BoucherS[CodePlex]</b> <br />Hi, 

This will be fixed in v2.7.

**Comment by xceedsoftware** [comment]
<b>AndreyLezhnev[CodePlex]</b> <br />Hi
I'm using Windows 7. And the failure is happening in th Toolkit v.2.4.
Thanks.

**Comment by xceedsoftware** [comment]
<b>BoucherS[CodePlex]</b> <br />Hi, 

Thanks for the sample.
I cannot reproduce in Windows 8. What version of Windows are you using ?
Was it happening in older version of the Toolkit... v2.3 and previous?
Thanks.

**Comment by xceedsoftware** [comment]
<b>AndreyLezhnev[CodePlex]</b> <br />I did not reproduce the issue playing in the LiveExplorer App. 
In the attachment your can find a simple app AvalonDockCrasher that use AvalonDock 2.4.0.0.


To reproduce the crash:

Run the AvalonDockCrasher in VS. In the AvalonDockCrasher take the Toolbox tool panel and move it out of the window to make it float.
Right click on desktop to open context menu, chose Personalize.
In the ControlPannel\Personalization window chose Windows Classic Theme. Wait until switching of the theme. In the ControlPannel\Personalization window chose Windows 7 (Aero) Theme. Wait until switching of the theme.
I have the Invalid Window Handle exception.

Thanks,
Andrey

**Comment by xceedsoftware** [comment]
<b>BoucherS[CodePlex]</b> <br />Hi, 

Can you reproduce this issue in the LiveExplorer App available here :https://wpftoolkit.codeplex.com/ in the sample Theming/AvalonDock Controls.


When you say : start switching back and forth between the classic Windows theme and an aero theme , what exactly do you do ? What are the exact steps ?


Thanks.

**Comment by startere** [comment]
Hello,

We are currently getting an error due to _hwndSource being disposed in WindowChromeWorker.cs (also it cannot be obtained again when it is checked to be disposed). The error occurs when using Remote Desktop Connection. No windows theme switching occurs.

Is there a workaround?
Has this been fixed? If so in which AvalonDock version?

Thanks,
Emil

**Comment by XceedBoucherS** [comment]
Hi,
Can you submit a sample and tell us how to reproduce this issue? Also, which version of the toolkit are you using ? Make sure to try the latest v3.8 version available for free for 45 days here : https://xceed.com/xceed-toolkit-plus-for-wpf/

**Comment by startere** [comment]
Hi,

Thanks for helping. We are using version 2.4 but we found you mentioned in your commit for version 2.9 that you fixed an issue very similar to the one we are experiencing(disconnecting-connecting using RDP). However the commit is very large and we could not find the specific location of the fix. Is it possible to indicate the diffs relating to the fix?
In https://github.com/xceedsoftware/wpftoolkit/wiki/improvements-in-v2.9.0
"In AvalonDock, LayoutAutoHideWindowControl won’t throw an invalid handle exception anymore upon disconnecting-reconnecting from a Virtual Machine."

We currently don`t have a stable repo, but at the first chance we have it we will send it. Until then we think applying the above fix from 2.9 might be useful.

Thanks,
Emil

**Comment by peteryangthinkgeo** [comment]
Hi @startere I met the same issue while using RDP, have you already resolved that? Can you tell me how to fix that?

**Comment by peteryangthinkgeo** [comment]
Hi @startere,
I figured out the reason about "invalid window handle" I met, I'd like to let you know and hope it can help you or others who met this issue.
**Just to bind Close event on the LayoutFloatingWindowControl to release the resource**. In my application I use MAF and the UI is an individual process. When running the application in RDP, the Unloaded event and Loaded event are triggered, and in the built-in Unloaded event, it tries to close the floating windows, but the individual process doesn't be close, and the UI tries to find the parent window which has been already released.

**Comment by XceedBoucherS** [comment]
Hi,
I can see the potential problem in LayoutFloatingWindowControl.OnUnloaded(), where a Close() is called.
Could you send a small sample and the steps to reproduce the issue so we can test it like you ?
Thank you.
