### ISSUE TITLE
Enter wrong value in DateTimePicker lead to applicatoin crash

### ISSUE THREAD

**Issue by xceedsoftware** [xceedsoftware/wpftoolkit#901]
<b>nickgrishaev[CodePlex]</b> <br />If in DateTimePicker user enter wrong text the application will crash.
Execution stack:

System.FormatException: String was not recognized as a valid DateTime.
at System.DateTime.Parse(String s, IFormatProvider provider)
at Xceed.Wpf.Toolkit.DateTimeUpDown.TryParseDateTime(String text, DateTimeamp result)
at Xceed.Wpf.Toolkit.DateTimeUpDown.IsCurrentValueValid()
at Xceed.Wpf.Toolkit.Core.Primitives.DateTimeUpDownBase`1.OnPreviewKeyDown(KeyEventArgs e)
at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
at System.Windows.Input.InputManager.ProcessStagingArea()
at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
at System.Windows.Interop.HwndKeyboardInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawKeyboardActions actions, Int32 scanCode, Boolean isExtendedKey, Boolean isSystemKey, Int32 virtualKey)
at System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSGamp msg, Booleanamp handled)
at System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSGamp msg, ModifierKeys modifiers)
at System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by xceedsoftware** [comment]
<b>BoucherS[CodePlex]</b> <br />Hi, 

Thanks for the sample and the screenshots of the Regions settings. 

This should be fixed in v2.7. 

In the meantime, you can go in file Xceed.Wpf.Toolkit/DatetimeUpDown/Implementation/DateTimeUpDown.cs, 
in method TryParseDateTime, 
replace the 2 lines :
DateTime current = this.Value.HasValue ? this.Value.Value : DateTime.Parse( this.ContextNow.ToString(), this.CultureInfo.DateTimeFormat );
      isValid = DateTimeParser.TryParse( text, this.GetFormatString( Format ), current, this.CultureInfo, out result );
with :
result = this.ContextNow;
      DateTime current = this.ContextNow;
      if( this.Value.HasValue )
      {
        current = this.Value.Value;
      }
      else
      {
        try
        {
          current = DateTime.Parse( this.ContextNow.ToString(), this.CultureInfo.DateTimeFormat );
          isValid = DateTimeParser.TryParse( text, this.GetFormatString( Format ), current, this.CultureInfo, out result );
        }
        catch( FormatException )
        {
          isValid = false;
        }
      }
and see if its better for your scenario.

**Comment by xceedsoftware** [comment]
<b>nickgrishaev[CodePlex]</b> <br />Test application attached

**Comment by xceedsoftware** [comment]
<b>nickgrishaev[CodePlex]</b> <br />The step needed to reproduce this bug: create empty WPF application (use .Net 4.5), add Wpf Extended Toolkit (v. 2.4) using NuGet.
Add DateTimePicker to the form:
Window x:Class=WPFtest.MainWindow
        xmlns=http://schemas.microsoft.com/winfx/2006/xaml/presentation
        xmlns:x=http://schemas.microsoft.com/winfx/2006/xaml
        xmlns:toolkit=http://schemas.xceed.com/wpf/xaml/toolkit
        Title=MainWindow Height=350 Width=525
    Grid
        toolkit:DateTimePicker  CultureInfo=(Default) FormatString=g
                      Format=Custom  Height=21 Width=200/
    /Grid
/Window
Start application and in DateTimePicker box type 22. (two two point), application crushed after . (point) entered in the box. If you type only 22 without . (point) – application does not crashed.



I think this bug depend on system regional setting.
My system regional settings attached. 


This is call stack of test application:
System.FormatException was unhandled
  HResult=-2146233033
  Message=String was not recognized as a valid DateTime.
  Source=mscorlib
  StackTrace:
       at System.DateTimeParse.Parse(String s, DateTimeFormatInfo dtfi, DateTimeStyles styles)
       at System.DateTime.Parse(String s, IFormatProvider provider)
       at Xceed.Wpf.Toolkit.DateTimeUpDown.TryParseDateTime(String text, DateTime result)
       at Xceed.Wpf.Toolkit.DateTimeUpDown.IsCurrentValueValid()
       at Xceed.Wpf.Toolkit.Core.Primitives.DateTimeUpDownBase`1.OnPreviewKeyDown(KeyEventArgs e)
       at Xceed.Wpf.Toolkit.DateTimePicker.OnPreviewKeyDown(KeyEventArgs e)
       at System.Windows.UIElement.OnPreviewKeyDownThunk(Object sender, KeyEventArgs e)
       at System.Windows.Input.KeyEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
       at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
       at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
       at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
       at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
       at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
       at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
       at System.Windows.Input.InputManager.ProcessStagingArea()
       at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
       at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
       at System.Windows.Interop.HwndKeyboardInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawKeyboardActions actions, Int32 scanCode, Boolean isExtendedKey, Boolean isSystemKey, Int32 virtualKey)
       at System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSG msg, Boolean handled)
       at System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSG msg, ModifierKeys modifiers)
       at System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
       at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
       at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
       at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
       at System.Windows.Threading.Dispatcher.Invoke(DispatcherPriority priority, Delegate method, Object arg)
       at System.Windows.Interop.HwndSource.OnPreprocessMessageThunk(MSG msg, Boolean handled)
       at System.Windows.Interop.HwndSource.WeakEventPreprocessMessage.OnPreprocessMessage(MSG msg, Boolean handled)
       at System.Windows.Interop.ComponentDispatcherThread.RaiseThreadMessage(MSG msg)
       at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
       at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
       at System.Windows.Threading.Dispatcher.Run()
       at System.Windows.Application.RunDispatcher(Object ignore)
       at System.Windows.Application.RunInternal(Window window)
       at System.Windows.Application.Run(Window window)
       at System.Windows.Application.Run()
       at WPFtest.App.Main() in f:\del\1\WPFtest\WPFtest\obj\Debug\App.g.cs:line 0
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException:

**Comment by xceedsoftware** [comment]
<b>BoucherS[CodePlex]</b> <br />Hi,
When you say that entering text 22 will crash the application, how do you enter this text ? Clicking on the TextBox from the DateTimePicker will automatically select a part of the DateTime value. Do you enter 22 for the year, the month,
 the minutes ? Or do you do a Ctrl-A to select all text and replace it with 22 ?


I cannot reproduce the issue. Can you submit a sample ?
Thanks

**Comment by xceedsoftware** [comment]
<b>nickgrishaev[CodePlex]</b> <br />If I remove CultureInfo=(Default) from code, bug not reproduced, but I have wrong date/time format (need to be US date\time format)
Test computer has Russian system locale

**Comment by xceedsoftware** [comment]
<b>nickgrishaev[CodePlex]</b> <br />Xaml code: 

toolkit:DateTimePicker x:Name=ExpirationDatePicker Grid.Column=3 Grid.Row=1 CultureInfo=(Default) Format=Custom FormatString=g Height=21

                                Value={Binding ExpirationDate, UpdateSourceTrigger=PropertyChanged, ValidatesOnDataErrors=True, NotifyOnValidationError=True}/

If I am enter text 22. application will crashed.
