### ISSUE TITLE
TimePicker crash when used Custom format and pressed Up/Down button

### ISSUE THREAD

**Issue by xceedsoftware** [xceedsoftware/wpftoolkit#939]
<b>tomas_maruska[CodePlex]</b> <br />When using TimePicker with Custom format and press Up or Down button application crash.

Exception:
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at Xceed.Wpf.Toolkit.DateTimeUpDown.UpdateDateTime(Int32 value)
   at Xceed.Wpf.Toolkit.DateTimeUpDown.OnDecrement()
   at Xceed.Wpf.Toolkit.Primitives.UpDownBase`1.DoDecrement()
   at Xceed.Wpf.Toolkit.Primitives.UpDownBase`1.OnSpin(SpinEventArgs e)
   at Xceed.Wpf.Toolkit.Primitives.UpDownBase`1.OnSpinnerSpin(Object sender, SpinEventArgs e)
   at Xceed.Wpf.Toolkit.Spinner.OnSpin(SpinEventArgs e)
   at Xceed.Wpf.Toolkit.ButtonSpinner.OnButtonClick(Object sender, RoutedEventArgs e)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Primitives.RepeatButton.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonDown(MouseButtonEventArgs e)
   at System.Windows.Controls.Primitives.RepeatButton.OnMouseLeftButtonDown(MouseButtonEventArgs e)
   at System.Windows.UIElement.OnMouseLeftButtonDownThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseDownThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Booleanamp handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Booleanamp handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Booleanamp handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
How to reproduce:

Create new WPF application and use following xaml in main window: 
ltWindow x:Class=quotWpfApplication2.MainWindowquot
        xmlns=quothttp://schemas.microsoft.com/winfx/2006/xaml/presentationquot
        xmlns:x=quothttp://schemas.microsoft.com/winfx/2006/xamlquot
        xmlns:xctk=quothttp://schemas.xceed.com/wpf/xaml/toolkitquot
        Title=quotMainWindowquot
        Width=quot525quot
        Height=quot350quotgt
    ltStackPanelgt
        ltxctk:TimePicker Format=quotCustomquot FormatString=quotHH:mm:ssquot /gt
    lt/StackPanelgt
lt/Windowgt

Click on Down button twice - application crash

Expected behavior:

Application does not crash and button will work :)

**Comment by xceedsoftware** [comment]
<b>BoucherS[CodePlex]</b> <br />Hi, 

This is already fixed.
Fix included in v2.6.

**Comment by Omcsesz** [comment]
I tried to reproduce the phenomenon with the given example code, but it works correctly.
