### ISSUE TITLE
Zoombox: NullReferenceException on SetScrollBars()

### ISSUE THREAD

**Issue by xceedsoftware** [xceedsoftware/wpftoolkit#940]
<b>ScholzFlo[CodePlex]</b> <br />With the new version 2.5 its not possible to use the zoombox. On every load the application crashes with following error:

at Xceed.Wpf.Toolkit.Zoombox.Zoombox.SetScrollBars()
at Xceed.Wpf.Toolkit.Zoombox.Zoombox.Zoombox_Loaded(Object sender, RoutedEventArgs e)
at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
at MS.Internal.LoadedOrUnloadedOperation.DoWork()
at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

I think it is coused beacouse _verticalScrollBar and _horizontalScrollBar are never been set!
Can you please fix it and load a new version on nuget?

Many thanks and best regards

**Comment by xceedsoftware** [comment]
<b>BoucherS[CodePlex]</b> <br />Hi, 

This is fixed in v2.7. 

Here's a workaround.
In file :
Xceed.Wpf.Toolkit/Zoombox/Zoombox.cs
in method :
SetScrollBars()
Make sure this method starts with :
if( _content == null || _verticalScrollBar == null || _horizontalScrollBar == null )
        return;
